import 'package:enya_gitarre_learn/core/models/exercise.dart';
import 'package:enya_gitarre_learn/core/models/lesson.dart';
import 'package:enya_gitarre_learn/core/models/module.dart';

/// Module 6 — "Offene Akkorde" (Wochen 7-10, Schwierigkeit 5).
/// Hauptpreset: CLEAN.
const String _moduleId = 'module-06';

final List<Lesson> module6Lessons = [
  Lesson(
    id: 'lesson-6-1',
    moduleId: _moduleId,
    title: 'Em — Der einfachste Akkord',
    description:
        'E-Moll ist der einfachste offene Akkord: zwei Finger, sechs klingende Saiten, voller Klang.',
    instructions: [
      'Mittelfinger auf A-Saite, Bund 2.',
      'Ringfinger auf D-Saite, Bund 2.',
      'Schlage alle sechs Saiten von oben nach unten an.',
      'Achte darauf, dass jede Saite klar klingt.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-1-1',
        lessonId: 'lesson-6-1',
        type: ExerciseType.chord,
        instructions: 'Spiele Em fünfmal sauber und klingend.',
        targetNoteOrChord: 'Em',
        bpm: 60,
        repetitionsRequired: 5,
        accuracyThreshold: 0.80,
        order: 1,
      ),
    ],
    xpReward: 80,
    difficulty: 4,
    targetAccuracy: 0.80,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['Em'],
    order: 1,
    isUnlocked: true,
    estimatedMinutes: 8,
  ),
  Lesson(
    id: 'lesson-6-2',
    moduleId: _moduleId,
    title: 'Am — A-Moll',
    description:
        'A-Moll: drei Finger, melancholischer Klang — ein Klassiker für ruhige Songs.',
    instructions: [
      'Zeigefinger auf H-Saite, Bund 1.',
      'Mittelfinger auf D-Saite, Bund 2.',
      'Ringfinger auf G-Saite, Bund 2.',
      'Schlage von der A-Saite an — die tiefe E-Saite bleibt stumm.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-2-1',
        lessonId: 'lesson-6-2',
        type: ExerciseType.chord,
        instructions: 'Spiele Am fünfmal mit klar klingenden Saiten.',
        targetNoteOrChord: 'Am',
        bpm: 60,
        repetitionsRequired: 5,
        accuracyThreshold: 0.80,
        order: 1,
      ),
    ],
    xpReward: 90,
    difficulty: 4,
    targetAccuracy: 0.80,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['Am'],
    order: 2,
    estimatedMinutes: 9,
  ),
  Lesson(
    id: 'lesson-6-3',
    moduleId: _moduleId,
    title: 'Em ↔ Am Wechsel',
    description:
        'Der erste echte Akkordwechsel: zwei Finger bleiben gleich, einer kommt dazu.',
    instructions: [
      'Beginne mit Em.',
      'Lege den Zeigefinger auf H-Saite Bund 1, die anderen Finger bleiben.',
      'Wechsle 8 Mal hin und her: Em - Am - Em - Am ...',
      'Ziel: flüssiger Wechsel ohne Pause.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-3-1',
        lessonId: 'lesson-6-3',
        type: ExerciseType.chord,
        instructions: 'Wechsle 8x zwischen Em und Am bei 60 BPM.',
        targetNoteOrChord: 'Em,Am',
        noteSequence: ['Em', 'Am', 'Em', 'Am', 'Em', 'Am', 'Em', 'Am'],
        bpm: 60,
        repetitionsRequired: 8,
        accuracyThreshold: 0.78,
        order: 1,
      ),
    ],
    xpReward: 110,
    difficulty: 4,
    targetAccuracy: 0.78,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['Em', 'Am'],
    order: 3,
    estimatedMinutes: 10,
  ),
  Lesson(
    id: 'lesson-6-4',
    moduleId: _moduleId,
    title: 'E-Dur',
    description:
        'E-Dur: derselbe Griff wie Em, plus ein Finger — und schon klingt es kraftvoll und hell.',
    instructions: [
      'Beginne mit Em.',
      'Lege den Zeigefinger zusätzlich auf G-Saite, Bund 1.',
      'Alle sechs Saiten klingen — schlage komplett an.',
      'Höre den Unterschied zwischen Em (traurig) und E (kraftvoll).',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-4-1',
        lessonId: 'lesson-6-4',
        type: ExerciseType.chord,
        instructions: 'Spiele E-Dur fünfmal sauber.',
        targetNoteOrChord: 'E',
        bpm: 60,
        repetitionsRequired: 5,
        accuracyThreshold: 0.80,
        order: 1,
      ),
    ],
    xpReward: 100,
    difficulty: 4,
    targetAccuracy: 0.80,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['E'],
    order: 4,
    estimatedMinutes: 9,
  ),
  Lesson(
    id: 'lesson-6-5',
    moduleId: _moduleId,
    title: 'D-Dur',
    description:
        'D-Dur: kompakte Dreiecksform auf den hohen Saiten — heller, klingender Akkord.',
    instructions: [
      'Zeigefinger auf G-Saite, Bund 2.',
      'Kleiner Finger auf H-Saite, Bund 3.',
      'Mittelfinger auf E-Saite (hoch), Bund 2.',
      'Schlage erst ab D-Saite — A und tiefe E bleiben stumm.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-5-1',
        lessonId: 'lesson-6-5',
        type: ExerciseType.chord,
        instructions: 'Spiele D-Dur fünfmal mit klarem Anschlag.',
        targetNoteOrChord: 'D',
        bpm: 60,
        repetitionsRequired: 5,
        accuracyThreshold: 0.80,
        order: 1,
      ),
    ],
    xpReward: 100,
    difficulty: 5,
    targetAccuracy: 0.80,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['D'],
    order: 5,
    estimatedMinutes: 10,
  ),
  Lesson(
    id: 'lesson-6-6',
    moduleId: _moduleId,
    title: 'G-Dur',
    description:
        'G-Dur: kraftvoller Akkord über alle sechs Saiten — Herzstück unzähliger Songs.',
    instructions: [
      'Mittelfinger auf tiefer E-Saite, Bund 3.',
      'Zeigefinger auf A-Saite, Bund 2.',
      'Ringfinger auf hoher E-Saite, Bund 3.',
      'D, G und H bleiben offen.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-6-1',
        lessonId: 'lesson-6-6',
        type: ExerciseType.chord,
        instructions: 'Spiele G-Dur fünfmal — alle sechs Saiten müssen klingen.',
        targetNoteOrChord: 'G',
        bpm: 60,
        repetitionsRequired: 5,
        accuracyThreshold: 0.78,
        order: 1,
      ),
    ],
    xpReward: 110,
    difficulty: 5,
    targetAccuracy: 0.78,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['G'],
    order: 6,
    estimatedMinutes: 11,
  ),
  Lesson(
    id: 'lesson-6-7',
    moduleId: _moduleId,
    title: 'C-Dur',
    description:
        'C-Dur: die klassische Dreifinger-Form — heller, freundlicher Klang.',
    instructions: [
      'Ringfinger auf A-Saite, Bund 3.',
      'Mittelfinger auf D-Saite, Bund 2.',
      'Zeigefinger auf H-Saite, Bund 1.',
      'Schlage ab A-Saite an — tiefe E bleibt stumm.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-7-1',
        lessonId: 'lesson-6-7',
        type: ExerciseType.chord,
        instructions: 'Spiele C-Dur fünfmal sauber.',
        targetNoteOrChord: 'C',
        bpm: 60,
        repetitionsRequired: 5,
        accuracyThreshold: 0.80,
        order: 1,
      ),
    ],
    xpReward: 110,
    difficulty: 5,
    targetAccuracy: 0.80,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['C'],
    order: 7,
    estimatedMinutes: 11,
  ),
  Lesson(
    id: 'lesson-6-8',
    moduleId: _moduleId,
    title: 'A-Dur',
    description:
        'A-Dur: drei Finger nebeneinander im 2. Bund — zunächst eng, mit Übung locker.',
    instructions: [
      'Zeigefinger auf D-Saite, Bund 2.',
      'Mittelfinger auf G-Saite, Bund 2.',
      'Ringfinger auf H-Saite, Bund 2.',
      'Schlage ab A-Saite an — tiefe E bleibt stumm.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-8-1',
        lessonId: 'lesson-6-8',
        type: ExerciseType.chord,
        instructions: 'Spiele A-Dur fünfmal sauber.',
        targetNoteOrChord: 'A',
        bpm: 60,
        repetitionsRequired: 5,
        accuracyThreshold: 0.78,
        order: 1,
      ),
    ],
    xpReward: 100,
    difficulty: 5,
    targetAccuracy: 0.78,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['A'],
    order: 8,
    estimatedMinutes: 10,
  ),
  Lesson(
    id: 'lesson-6-9',
    moduleId: _moduleId,
    title: 'Dm — D-Moll',
    description:
        'D-Moll: die traurigste Schwester von D-Dur — kompakt und gefühlvoll.',
    instructions: [
      'Zeigefinger auf hoher E-Saite, Bund 1.',
      'Mittelfinger auf G-Saite, Bund 2.',
      'Ringfinger auf H-Saite, Bund 3.',
      'Schlage ab D-Saite an.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-9-1',
        lessonId: 'lesson-6-9',
        type: ExerciseType.chord,
        instructions: 'Spiele Dm fünfmal sauber.',
        targetNoteOrChord: 'Dm',
        bpm: 60,
        repetitionsRequired: 5,
        accuracyThreshold: 0.80,
        order: 1,
      ),
    ],
    xpReward: 100,
    difficulty: 5,
    targetAccuracy: 0.80,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['Dm'],
    order: 9,
    estimatedMinutes: 10,
  ),
  Lesson(
    id: 'lesson-6-10',
    moduleId: _moduleId,
    title: 'Akkordwechsel-Speed-Trainer',
    description:
        'Trainiere flüssige Akkordwechsel im Tempo: G - C - D - Em im 4-Takt-Wechsel.',
    instructions: [
      'Spiele jeden Akkord genau einen Takt (4 Schläge).',
      'Wechsle ohne Pause zwischen den Akkorden.',
      'Beginne langsam (60 BPM), erhöhe schrittweise auf 90 BPM.',
      'Saubere Wechsel sind wichtiger als Tempo.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-10-1',
        lessonId: 'lesson-6-10',
        type: ExerciseType.chord,
        instructions: 'Spiele G - C - D - Em vier Durchgänge bei 80 BPM.',
        targetNoteOrChord: 'G,C,D,Em',
        noteSequence: ['G', 'C', 'D', 'Em'],
        bpm: 80,
        repetitionsRequired: 4,
        accuracyThreshold: 0.78,
        timeoutSeconds: 90,
        order: 1,
      ),
    ],
    xpReward: 160,
    difficulty: 5,
    targetAccuracy: 0.78,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['G', 'C', 'D', 'Em'],
    order: 10,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-6-11',
    moduleId: _moduleId,
    title: "Knockin' on Heaven's Door",
    description:
        'Bob Dylans Klassiker mit nur vier Akkorden: G - D - Am - C im endlosen Loop.',
    instructions: [
      'Akkordfolge: G - D - Am - G - D - C.',
      'Strumming: Down-Down-Up-Up-Down-Up im 4/4-Takt.',
      'Halte das Tempo bei 80 BPM.',
      'Genieße die einfache Schönheit dieses Songs.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-11-1',
        lessonId: 'lesson-6-11',
        type: ExerciseType.chord,
        instructions: 'Spiele die Akkordfolge dreimal komplett durch.',
        targetNoteOrChord: 'G,D,Am,G,D,C',
        noteSequence: ['G', 'D', 'Am', 'G', 'D', 'C'],
        bpm: 80,
        repetitionsRequired: 3,
        accuracyThreshold: 0.78,
        timeoutSeconds: 120,
        order: 1,
      ),
    ],
    xpReward: 200,
    difficulty: 5,
    targetAccuracy: 0.78,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['G', 'D', 'Am', 'C'],
    order: 11,
    estimatedMinutes: 16,
  ),
  Lesson(
    id: 'lesson-6-12',
    moduleId: _moduleId,
    title: 'Wonderful Tonight',
    description:
        'Eric Claptons romantische Ballade — G - D - C - D als Hauptloop.',
    instructions: [
      'Akkordfolge: G - D - C - D, jeweils einen Takt lang.',
      'Spiele weich und ohne harten Anschlag.',
      'Strumming: ↓ ↓ ↑ ↑ ↓ ↑.',
      'Tempo: 75 BPM für die richtige Stimmung.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-12-1',
        lessonId: 'lesson-6-12',
        type: ExerciseType.chord,
        instructions: 'Spiele G - D - C - D vier Durchgänge im richtigen Groove.',
        targetNoteOrChord: 'G,D,C,D',
        noteSequence: ['G', 'D', 'C', 'D'],
        bpm: 75,
        repetitionsRequired: 4,
        accuracyThreshold: 0.78,
        timeoutSeconds: 90,
        order: 1,
      ),
    ],
    xpReward: 200,
    difficulty: 5,
    targetAccuracy: 0.78,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['G', 'D', 'C'],
    order: 12,
    estimatedMinutes: 15,
  ),
  Lesson(
    id: 'lesson-6-13',
    moduleId: _moduleId,
    title: 'Horse With No Name',
    description:
        'America-Klassiker mit nur zwei Akkorden: Em und D6/9 — meditativ und endlos.',
    instructions: [
      'Akkord 1: Em wie gewohnt.',
      'Akkord 2: D6/9 — Zeigefinger auf G-Saite Bund 2, Mittelfinger auf hoher E Bund 2.',
      'Wechsle alle 2 Takte zwischen den beiden.',
      'Strumming-Pattern beibehalten — der Wechsel macht den Vibe.',
    ],
    exercises: [
      Exercise(
        id: 'ex-6-13-1',
        lessonId: 'lesson-6-13',
        type: ExerciseType.chord,
        instructions: 'Wechsle 8 Mal zwischen Em und D6/9 sauber.',
        targetNoteOrChord: 'Em,D',
        noteSequence: ['Em', 'D', 'Em', 'D', 'Em', 'D', 'Em', 'D'],
        bpm: 80,
        repetitionsRequired: 8,
        accuracyThreshold: 0.78,
        timeoutSeconds: 90,
        order: 1,
      ),
    ],
    xpReward: 200,
    difficulty: 5,
    targetAccuracy: 0.78,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['Em', 'D'],
    order: 13,
    estimatedMinutes: 14,
  ),
];

final Module module6 = Module(
  id: _moduleId,
  moduleNumber: 6,
  title: 'Offene Akkorde',
  description:
      'Lerne die wichtigsten offenen Akkorde: Em, Am, E, D, G, C, A, Dm — und drei klassische Songs.',
  weekRange: 'Woche 7-10',
  presetRequired: GuitarPreset.clean,
  difficulty: 5,
  isLocked: true,
  unlockedPresets: const [],
  learningGoals:
      'Acht offene Akkorde, flüssige Wechsel, drei berühmte Songs spielen.',
  lessons: module6Lessons,
);
