import 'package:enya_gitarre_learn/core/models/exercise.dart';
import 'package:enya_gitarre_learn/core/models/lesson.dart';
import 'package:enya_gitarre_learn/core/models/module.dart';

/// Module 7 — "Barré-Akkorde" (Wochen 11-14, Schwierigkeit 7).
/// Hauptpresets: CLEAN + OVERDRIVE.
const String _moduleId = 'module-07';

final List<Lesson> module7Lessons = [
  Lesson(
    id: 'lesson-7-1',
    moduleId: _moduleId,
    title: 'Was ist ein Barré',
    description:
        'Verstehe das Prinzip: ein Finger ersetzt den Sattel und ermöglicht jede Akkordform überall auf dem Griffbrett.',
    instructions: [
      'Der Zeigefinger drückt mehrere Saiten gleichzeitig — wie ein "Kapodaster aus Fleisch".',
      'Die anderen Finger formen einen bekannten Akkord oberhalb.',
      'Mit Barré kannst du Dur- und Moll-Akkorde an jedem Bund spielen.',
      'Diese Lektion ist Theorie — keine Übung am Instrument nötig.',
    ],
    exercises: [
      Exercise(
        id: 'ex-7-1-1',
        lessonId: 'lesson-7-1',
        type: ExerciseType.earTraining,
        instructions:
            'Höre dir Beispiele von Barré-Akkorden in verschiedenen Lagen an.',
        targetNoteOrChord: 'F',
        bpm: 60,
        repetitionsRequired: 1,
        accuracyThreshold: 0.70,
        order: 1,
      ),
    ],
    xpReward: 60,
    difficulty: 5,
    targetAccuracy: 0.70,
    presetRequired: GuitarPreset.clean,
    order: 1,
    isUnlocked: true,
    estimatedMinutes: 6,
  ),
  Lesson(
    id: 'lesson-7-2',
    moduleId: _moduleId,
    title: 'Barré-Vorübung',
    description:
        'Trainiere die Kraft im Zeigefinger, bevor du den ersten Barré-Akkord greifst.',
    instructions: [
      'Lege den Zeigefinger flach über alle 6 Saiten am 5. Bund.',
      'Drücke gleichmäßig — jede Saite muss klingen, wenn du sie einzeln zupfst.',
      'Halte 10 Sekunden, dann entspannen.',
      'Wiederhole fünfmal — Geduld zahlt sich aus.',
    ],
    exercises: [
      Exercise(
        id: 'ex-7-2-1',
        lessonId: 'lesson-7-2',
        type: ExerciseType.singleNote,
        instructions: 'Zupfe alle 6 Saiten einzeln im Barré am 5. Bund — 5 Durchgänge.',
        targetNoteOrChord: 'A',
        bpm: 50,
        repetitionsRequired: 5,
        accuracyThreshold: 0.70,
        order: 1,
      ),
    ],
    xpReward: 100,
    difficulty: 6,
    targetAccuracy: 0.70,
    presetRequired: GuitarPreset.clean,
    order: 2,
    estimatedMinutes: 10,
  ),
  Lesson(
    id: 'lesson-7-3',
    moduleId: _moduleId,
    title: 'F-Dur — Der erste Barré',
    description:
        'F-Dur ist der berüchtigte erste Barré — meistere ihn und du meisterst die Gitarre.',
    instructions: [
      'Zeigefinger Barré über alle Saiten am 1. Bund.',
      'Mittelfinger auf G-Saite, Bund 2.',
      'Ringfinger auf A-Saite, Bund 3.',
      'Kleiner Finger auf D-Saite, Bund 3.',
    ],
    exercises: [
      Exercise(
        id: 'ex-7-3-1',
        lessonId: 'lesson-7-3',
        type: ExerciseType.chord,
        instructions: 'Spiele F-Dur fünfmal — alle Saiten müssen klingen.',
        targetNoteOrChord: 'F',
        bpm: 50,
        repetitionsRequired: 5,
        accuracyThreshold: 0.70,
        order: 1,
      ),
    ],
    xpReward: 200,
    difficulty: 7,
    targetAccuracy: 0.70,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['F'],
    order: 3,
    estimatedMinutes: 15,
  ),
  Lesson(
    id: 'lesson-7-4',
    moduleId: _moduleId,
    title: 'E-Form verschiebbar',
    description:
        'Die E-Form als Barré: F am 1. Bund, G am 3. Bund, A am 5. — eine Form, alle Dur-Akkorde.',
    instructions: [
      'Greife F-Dur in der E-Form am 1. Bund.',
      'Verschiebe die ganze Form Bund für Bund nach oben.',
      '3. Bund = G, 5. Bund = A, 7. Bund = H.',
      'Die Position des Barré bestimmt den Grundton (tiefe E-Saite).',
    ],
    exercises: [
      Exercise(
        id: 'ex-7-4-1',
        lessonId: 'lesson-7-4',
        type: ExerciseType.chord,
        instructions: 'Spiele F - G - A - G - F mit E-Form-Barré.',
        targetNoteOrChord: 'F,G,A',
        noteSequence: ['F', 'G', 'A', 'G', 'F'],
        bpm: 60,
        repetitionsRequired: 3,
        accuracyThreshold: 0.72,
        timeoutSeconds: 90,
        order: 1,
      ),
    ],
    xpReward: 200,
    difficulty: 7,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['F', 'G', 'A'],
    order: 4,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-7-5',
    moduleId: _moduleId,
    title: 'Em-Form verschiebbar',
    description:
        'Die Em-Form als Barré: jeder Moll-Akkord am Griffbrett — Fm, Gm, Am, Bm.',
    instructions: [
      'Greife Em ohne den eigentlichen Em-Griff: Mittelfinger und Ringfinger auf A und D-Saite, jeweils Bund 2 (relativ zum Barré).',
      'Setze den Barré am 1. Bund: Fm. Am 3. Bund: Gm. Am 5. Bund: Am.',
      'Die hohe E-Saite klingt mit, da der Barré sie greift.',
      'Achte auf einen sauberen, kompletten Klang.',
    ],
    exercises: [
      Exercise(
        id: 'ex-7-5-1',
        lessonId: 'lesson-7-5',
        type: ExerciseType.chord,
        instructions: 'Spiele Fm - Gm - Am mit Em-Form-Barré.',
        targetNoteOrChord: 'Fm,Gm,Am',
        noteSequence: ['Fm', 'Gm', 'Am'],
        bpm: 60,
        repetitionsRequired: 3,
        accuracyThreshold: 0.72,
        timeoutSeconds: 60,
        order: 1,
      ),
    ],
    xpReward: 200,
    difficulty: 7,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['Fm', 'Gm', 'Am'],
    order: 5,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-7-6',
    moduleId: _moduleId,
    title: 'A-Form Barré',
    description:
        'Die A-Form als Barré: Grundton auf der A-Saite — H-Dur, C-Dur, D-Dur in einer Form.',
    instructions: [
      'Zeigefinger Barré ab A-Saite — die tiefe E-Saite bleibt stumm.',
      'Ring- oder kleiner Finger als Mini-Barré auf D-, G- und H-Saite zwei Bünde höher.',
      '2. Bund = H, 3. Bund = C, 5. Bund = D.',
      'Die A-Form-Barrés klingen heller als die E-Form-Barrés.',
    ],
    exercises: [
      Exercise(
        id: 'ex-7-6-1',
        lessonId: 'lesson-7-6',
        type: ExerciseType.chord,
        instructions: 'Spiele B (H) - C - D - C - B mit A-Form-Barré.',
        targetNoteOrChord: 'B,C,D',
        noteSequence: ['B', 'C', 'D', 'C', 'B'],
        bpm: 60,
        repetitionsRequired: 3,
        accuracyThreshold: 0.72,
        timeoutSeconds: 90,
        order: 1,
      ),
    ],
    xpReward: 200,
    difficulty: 7,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.clean,
    chordIds: const ['B', 'C', 'D'],
    order: 6,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-7-7',
    moduleId: _moduleId,
    title: 'Creep — Radiohead',
    description:
        'Der Klassiker mit nur vier Akkorden, davon zwei Barrés: G - B - C - Cm.',
    instructions: [
      'G-Dur als offener Akkord.',
      'H-Dur (B) als A-Form-Barré am 2. Bund.',
      'C-Dur als A-Form-Barré am 3. Bund.',
      'Cm als A-Moll-Form-Barré am 3. Bund — der "Creep"-Twist.',
    ],
    exercises: [
      Exercise(
        id: 'ex-7-7-1',
        lessonId: 'lesson-7-7',
        type: ExerciseType.chord,
        instructions: 'Spiele G - B - C - Cm vier Durchgänge im Tempo.',
        targetNoteOrChord: 'G,B,C,Cm',
        noteSequence: ['G', 'B', 'C', 'Cm'],
        bpm: 90,
        repetitionsRequired: 4,
        accuracyThreshold: 0.75,
        timeoutSeconds: 120,
        order: 1,
      ),
    ],
    xpReward: 280,
    difficulty: 7,
    targetAccuracy: 0.75,
    presetRequired: GuitarPreset.overdrive,
    chordIds: const ['G', 'B', 'C', 'Cm'],
    order: 7,
    estimatedMinutes: 18,
  ),
];

final Module module7 = Module(
  id: _moduleId,
  moduleNumber: 7,
  title: 'Barré-Akkorde',
  description:
      'Meistere Barré-Akkorde — F-Dur, verschiebbare E- und A-Formen, und der berühmte "Creep"-Song.',
  weekRange: 'Woche 11-14',
  presetRequired: GuitarPreset.clean,
  difficulty: 7,
  isLocked: true,
  unlockedPresets: const [],
  learningGoals:
      'Barré-Technik, F-Dur, verschiebbare E-/Em-/A-Formen, Song "Creep".',
  lessons: module7Lessons,
);
