import 'package:enya_gitarre_learn/core/models/exercise.dart';
import 'package:enya_gitarre_learn/core/models/lesson.dart';
import 'package:enya_gitarre_learn/core/models/module.dart';

/// Module 11 — "High-Gain & Fortgeschritten" (Wochen 29-36, Schwierigkeit 8).
/// Hauptpreset: HIGH-GAIN.
const String _moduleId = 'module-11';

final List<Lesson> module11Lessons = [
  Lesson(
    id: 'lesson-11-1',
    moduleId: _moduleId,
    title: 'Schnelles Alternate Picking',
    description:
        'Konsequenter Wechselschlag bei hohem Tempo — die Grundlage jeder Lead-Technik.',
    instructions: [
      'Pattern: streng abwechselnd Down-Up-Down-Up.',
      'Übe auf einer Saite chromatische Töne (1-2-3-4 pro Saite).',
      'Beginne bei 80 BPM, steigere bis 160 BPM.',
      'Saubere Töne wichtiger als Geschwindigkeit.',
    ],
    exercises: [
      Exercise(
        id: 'ex-11-1-1',
        lessonId: 'lesson-11-1',
        type: ExerciseType.singleNote,
        instructions: 'Spiele 16 chromatische Sechzehntel pro Saite bei 120 BPM.',
        targetNoteOrChord: 'A3',
        bpm: 120,
        repetitionsRequired: 16,
        accuracyThreshold: 0.74,
        order: 1,
      ),
    ],
    xpReward: 220,
    difficulty: 8,
    targetAccuracy: 0.74,
    presetRequired: GuitarPreset.highGain,
    order: 1,
    isUnlocked: true,
    estimatedMinutes: 16,
  ),
  Lesson(
    id: 'lesson-11-2',
    moduleId: _moduleId,
    title: 'String Skipping',
    description:
        'Überspringe Saiten beim Picking — eröffnet weite Intervall-Sprünge in Soli.',
    instructions: [
      'Spiele E-Saite Bund 5, dann D-Saite Bund 5 (überspringt A).',
      'Übe das Pattern auf und ab.',
      'Achte darauf, dass die übersprungene Saite nicht klingt.',
      'Mit Distortion klingt jeder Fehler doppelt — sauber bleiben.',
    ],
    exercises: [
      Exercise(
        id: 'ex-11-2-1',
        lessonId: 'lesson-11-2',
        type: ExerciseType.singleNote,
        instructions: 'Spiele 12 String-Skip-Patterns bei 100 BPM.',
        targetNoteOrChord: 'A3',
        bpm: 100,
        repetitionsRequired: 12,
        accuracyThreshold: 0.72,
        order: 1,
      ),
    ],
    xpReward: 200,
    difficulty: 8,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.highGain,
    order: 2,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-11-3',
    moduleId: _moduleId,
    title: 'Tapping Basics',
    description:
        'Eddie Van Halens Geheimwaffe: Töne mit der rechten Hand auf das Griffbrett "tappen".',
    instructions: [
      'Greife mit links Bund 5 G-Saite.',
      'Tappe mit dem rechten Zeigefinger Bund 12, ziehe ihn schnell weg (Pull-Off).',
      'Pull-Off auf den linken Finger zurück — drei Töne mit einem Tap.',
      'Üben, bis das Tap-Pattern flüssig läuft.',
    ],
    exercises: [
      Exercise(
        id: 'ex-11-3-1',
        lessonId: 'lesson-11-3',
        type: ExerciseType.singleNote,
        instructions: 'Spiele 10 Tapping-Patterns auf G-Saite.',
        targetNoteOrChord: 'C4',
        bpm: 90,
        repetitionsRequired: 10,
        accuracyThreshold: 0.70,
        order: 1,
      ),
    ],
    xpReward: 240,
    difficulty: 8,
    targetAccuracy: 0.70,
    presetRequired: GuitarPreset.highGain,
    order: 3,
    estimatedMinutes: 16,
  ),
  Lesson(
    id: 'lesson-11-4',
    moduleId: _moduleId,
    title: 'Zwei-Hand-Tapping',
    description:
        'Beide Hände tappen: schnellste, fließendste Lines mit minimalem Aufwand.',
    instructions: [
      'Linke Hand tappt zwei Töne (Bund 5 + 7).',
      'Rechte Hand tappt einen Ton (Bund 12).',
      'Triolen-Feeling: 3 Töne pro Beat.',
      'Sehr langsam üben — Geschwindigkeit kommt automatisch.',
    ],
    exercises: [
      Exercise(
        id: 'ex-11-4-1',
        lessonId: 'lesson-11-4',
        type: ExerciseType.singleNote,
        instructions: 'Spiele 12 Zwei-Hand-Tap-Triolen bei 100 BPM.',
        targetNoteOrChord: 'E4',
        bpm: 100,
        repetitionsRequired: 12,
        accuracyThreshold: 0.70,
        order: 1,
      ),
    ],
    xpReward: 260,
    difficulty: 8,
    targetAccuracy: 0.70,
    presetRequired: GuitarPreset.highGain,
    order: 4,
    estimatedMinutes: 18,
  ),
  Lesson(
    id: 'lesson-11-5',
    moduleId: _moduleId,
    title: 'Dur-Pentatonik',
    description:
        'Die hellere Schwester der Moll-Pentatonik — perfekt für Country, Rock und Pop-Soli.',
    instructions: [
      'G-Dur-Pentatonik = E-Moll-Pentatonik, nur mit anderem "Heimat-Ton".',
      'Position 1 ab Bund 3 tiefe E-Saite.',
      'Töne: G - A - B - D - E.',
      'Spiele über G-Dur-Akkordfolgen.',
    ],
    exercises: [
      Exercise(
        id: 'ex-11-5-1',
        lessonId: 'lesson-11-5',
        type: ExerciseType.scale,
        instructions: 'Spiele die G-Dur-Pentatonik 3x auf und ab.',
        targetNoteOrChord: 'G,A,B,D,E',
        noteSequence: ['G3', 'A3', 'B3', 'D4', 'E4', 'G4'],
        bpm: 90,
        repetitionsRequired: 3,
        accuracyThreshold: 0.76,
        order: 1,
      ),
    ],
    xpReward: 200,
    difficulty: 7,
    targetAccuracy: 0.76,
    presetRequired: GuitarPreset.highGain,
    scaleIds: const ['G-major-pent'],
    order: 5,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-11-6',
    moduleId: _moduleId,
    title: 'Blues-Tonleiter',
    description:
        'Pentatonik plus Blue Note (b5) — der schmutzige, soulige Sound des Blues.',
    instructions: [
      'A-Moll-Pentatonik + zusätzlich Eb (b5) zwischen D und E.',
      'Diese Note ist der "Blue Note" — sparsam einsetzen.',
      'Übe das Pattern auf der A- und G-Saite.',
      'Mit Bending klingt die Blue Note besonders heftig.',
    ],
    exercises: [
      Exercise(
        id: 'ex-11-6-1',
        lessonId: 'lesson-11-6',
        type: ExerciseType.scale,
        instructions: 'Spiele die A-Blues-Tonleiter 3x mit Blue Note.',
        targetNoteOrChord: 'A,C,D,Eb,E,G',
        noteSequence: ['A2', 'C3', 'D3', 'Eb3', 'E3', 'G3', 'A3'],
        bpm: 80,
        repetitionsRequired: 3,
        accuracyThreshold: 0.74,
        order: 1,
      ),
    ],
    xpReward: 220,
    difficulty: 7,
    targetAccuracy: 0.74,
    presetRequired: GuitarPreset.highGain,
    scaleIds: const ['A-blues'],
    order: 6,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-11-7',
    moduleId: _moduleId,
    title: 'Sweep Picking Einführung',
    description:
        'Streiche das Plektrum durch mehrere Saiten in einer fließenden Bewegung — der Sound von Yngwie Malmsteen.',
    instructions: [
      'Beginne mit einem 3-Saiten-Sweep auf einer Moll-Akkord-Form.',
      'Down-Stroke gleitet von G- über H- bis hohe E-Saite.',
      'Linke Hand drückt jeden Ton kurz und löst sofort wieder — keine Klangüberlappung.',
      'Sehr langsam üben (60 BPM) — Sweep braucht Präzision.',
    ],
    exercises: [
      Exercise(
        id: 'ex-11-7-1',
        lessonId: 'lesson-11-7',
        type: ExerciseType.singleNote,
        instructions: 'Spiele 8 saubere 3-Saiten-Sweeps bei 60 BPM.',
        targetNoteOrChord: 'A,C,E',
        bpm: 60,
        repetitionsRequired: 8,
        accuracyThreshold: 0.68,
        order: 1,
      ),
    ],
    xpReward: 280,
    difficulty: 9,
    targetAccuracy: 0.68,
    presetRequired: GuitarPreset.highGain,
    order: 7,
    estimatedMinutes: 20,
  ),
  Lesson(
    id: 'lesson-11-8',
    moduleId: _moduleId,
    title: 'Solo: Sweet Child O\' Mine',
    description:
        'Slashs Solo — eines der berühmtesten Rock-Soli aller Zeiten in D-Dur-Pentatonik.',
    instructions: [
      'Beginne mit dem ikonischen Intro-Lick (Bund 12-15 hohe E-Saite).',
      'Verwende viele Bendings und Vibrato.',
      'Tempo schrittweise steigern auf das Original (122 BPM).',
      'Verstehe die Phrasierung — sie macht das Solo so berühmt.',
    ],
    exercises: [
      Exercise(
        id: 'ex-11-8-1',
        lessonId: 'lesson-11-8',
        type: ExerciseType.scale,
        instructions: 'Spiele das Solo-Hauptthema dreimal sauber durch.',
        targetNoteOrChord: 'D,E,F#,A,B',
        bpm: 110,
        repetitionsRequired: 3,
        accuracyThreshold: 0.72,
        timeoutSeconds: 240,
        order: 1,
      ),
    ],
    xpReward: 320,
    difficulty: 8,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.highGain,
    scaleIds: const ['D-major-pent'],
    order: 8,
    estimatedMinutes: 26,
  ),
  Lesson(
    id: 'lesson-11-9',
    moduleId: _moduleId,
    title: 'Solo: Nothing Else Matters',
    description:
        'Kirk Hammetts gefühlvolles Solo aus Metallicas Ballade — eMoll-Pentatonik mit viel Vibrato.',
    instructions: [
      'Beginne mit Em-Pentatonik in der ersten Position.',
      'Phrasen mit viel Vibrato auf langen Tönen.',
      'Sanfte Dynamik — nicht zu aggressiv.',
      'Tempo: ca. 70 BPM, langsam und ausdrucksstark.',
    ],
    exercises: [
      Exercise(
        id: 'ex-11-9-1',
        lessonId: 'lesson-11-9',
        type: ExerciseType.scale,
        instructions: 'Spiele das Solo zweimal mit ausdrucksstarkem Vibrato.',
        targetNoteOrChord: 'E,G,A,B,D',
        bpm: 70,
        repetitionsRequired: 2,
        accuracyThreshold: 0.72,
        timeoutSeconds: 240,
        order: 1,
      ),
    ],
    xpReward: 320,
    difficulty: 8,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.highGain,
    scaleIds: const ['Em-pent'],
    order: 9,
    estimatedMinutes: 26,
  ),
];

final Module module11 = Module(
  id: _moduleId,
  moduleNumber: 11,
  title: 'High-Gain & Fortgeschritten',
  description:
      'Schnelles Picking, Tapping, Sweep, Dur-Pentatonik, Blues-Tonleiter — und zwei legendäre Soli.',
  weekRange: 'Woche 29-36',
  presetRequired: GuitarPreset.highGain,
  difficulty: 8,
  isLocked: true,
  unlockedPresets: const [],
  learningGoals:
      'Alternate Picking, String Skipping, Tapping, Sweep, Dur-Pentatonik, Blues-Tonleiter, Soli "Sweet Child O\' Mine" und "Nothing Else Matters".',
  lessons: module11Lessons,
);
