import 'package:enya_gitarre_learn/core/models/exercise.dart';
import 'package:enya_gitarre_learn/core/models/lesson.dart';
import 'package:enya_gitarre_learn/core/models/module.dart';

/// Module 8 — "Pentatonik & Solo-Basics" (Wochen 15-18, Schwierigkeit 6).
/// Hauptpreset: OVERDRIVE; DISTORTION wird in Lektion 8.10 freigeschaltet.
const String _moduleId = 'module-08';

final List<Lesson> module8Lessons = [
  Lesson(
    id: 'lesson-8-1',
    moduleId: _moduleId,
    title: 'Was ist eine Tonleiter?',
    description:
        'Eine Tonleiter ist eine geordnete Folge von Tönen — die Grundlage jedes Solos und jeder Melodie.',
    instructions: [
      'Töne sind nicht zufällig — sie folgen Mustern.',
      'Die wichtigste Tonleiter im Rock: die Moll-Pentatonik.',
      'Pentatonik = 5 Töne (vom griechischen "penta").',
      'Diese Lektion ist Theorie — keine Übung am Instrument nötig.',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-1-1',
        lessonId: 'lesson-8-1',
        type: ExerciseType.earTraining,
        instructions: 'Höre Beispiele der Moll-Pentatonik in verschiedenen Tonarten.',
        targetNoteOrChord: 'Am',
        bpm: 80,
        repetitionsRequired: 1,
        accuracyThreshold: 0.70,
        order: 1,
      ),
    ],
    xpReward: 60,
    difficulty: 4,
    targetAccuracy: 0.70,
    presetRequired: GuitarPreset.overdrive,
    order: 1,
    isUnlocked: true,
    estimatedMinutes: 6,
  ),
  Lesson(
    id: 'lesson-8-2',
    moduleId: _moduleId,
    title: 'Moll-Pentatonik Position 1',
    description:
        'Die A-Moll-Pentatonik in der ersten Lage — das Standard-Pattern für Solos im Rock.',
    instructions: [
      'Beginne am 5. Bund der tiefen E-Saite (A).',
      'Pattern: 5-8 / 5-7 / 5-7 / 5-7 / 5-8 / 5-8.',
      'Spiele jede Saite langsam und sauber.',
      'Übe das Pattern auf und ab — auswendig lernen!',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-2-1',
        lessonId: 'lesson-8-2',
        type: ExerciseType.scale,
        instructions: 'Spiele die A-Moll-Pentatonik aufwärts und abwärts, 3x.',
        targetNoteOrChord: 'A,C,D,E,G',
        noteSequence: ['A2', 'C3', 'D3', 'E3', 'G3', 'A3', 'C4', 'D4', 'E4', 'G4'],
        bpm: 70,
        repetitionsRequired: 3,
        accuracyThreshold: 0.78,
        order: 1,
      ),
    ],
    xpReward: 150,
    difficulty: 5,
    targetAccuracy: 0.78,
    presetRequired: GuitarPreset.overdrive,
    scaleIds: const ['Am-pent-pos1'],
    order: 2,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-8-3',
    moduleId: _moduleId,
    title: 'Pentatonik mit Backing Track',
    description:
        'Spiele die Pentatonik über einen Am-Backing-Track — dein erstes echtes Solo-Feeling.',
    instructions: [
      'Der Backing Track läuft in A-Moll.',
      'Spiele frei mit den Tönen der Pentatonik.',
      'Halte den Rhythmus, lasse Pausen zu.',
      'Es gibt keine falschen Töne in dieser Skala — experimentiere.',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-3-1',
        lessonId: 'lesson-8-3',
        type: ExerciseType.scale,
        instructions: 'Improvisiere 60 Sekunden zur Backing Track.',
        targetNoteOrChord: 'A,C,D,E,G',
        bpm: 90,
        repetitionsRequired: 1,
        accuracyThreshold: 0.70,
        timeoutSeconds: 90,
        order: 1,
      ),
    ],
    xpReward: 180,
    difficulty: 6,
    targetAccuracy: 0.70,
    presetRequired: GuitarPreset.overdrive,
    scaleIds: const ['Am-pent-pos1'],
    order: 3,
    estimatedMinutes: 12,
  ),
  Lesson(
    id: 'lesson-8-4',
    moduleId: _moduleId,
    title: 'Bending — Saiten ziehen',
    description:
        'Das Geheimnis emotionaler Soli: ziehe eine Saite in Richtung Decke und der Ton wird höher.',
    instructions: [
      'Greife einen Ton mit Ringfinger, unterstütze mit Mittel- und Zeigefinger.',
      'Ziehe die Saite nach oben oder unten — ein Halbton oder ein Ganzton.',
      'Vergleiche mit dem Zielton (zwei Bünde höher).',
      'Übe an der G-Saite, 7. Bund — bende auf den Klang von Bund 9.',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-4-1',
        lessonId: 'lesson-8-4',
        type: ExerciseType.singleNote,
        instructions: 'Mache 10 Ganzton-Bendings auf G-Saite Bund 7 zur Tonhöhe von Bund 9.',
        targetNoteOrChord: 'A3',
        bpm: 60,
        repetitionsRequired: 10,
        accuracyThreshold: 0.72,
        order: 1,
      ),
    ],
    xpReward: 180,
    difficulty: 6,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.overdrive,
    order: 4,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-8-5',
    moduleId: _moduleId,
    title: 'Vibrato',
    description:
        'Der finale Ton-Schliff: lass die Note durch leichtes Wackeln lebendig werden.',
    instructions: [
      'Greife einen Ton fest auf dem Bund.',
      'Bewege die Saite minimal hoch und runter — wie ein Mini-Bending.',
      'Gleichmäßig und kontrolliert — nicht zu schnell.',
      'Vibrato verleiht jedem Ton Persönlichkeit.',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-5-1',
        lessonId: 'lesson-8-5',
        type: ExerciseType.singleNote,
        instructions: 'Spiele 10 Töne mit Vibrato — A auf G-Saite Bund 2.',
        targetNoteOrChord: 'A3',
        bpm: 60,
        repetitionsRequired: 10,
        accuracyThreshold: 0.72,
        order: 1,
      ),
    ],
    xpReward: 160,
    difficulty: 6,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.overdrive,
    order: 5,
    estimatedMinutes: 12,
  ),
  Lesson(
    id: 'lesson-8-6',
    moduleId: _moduleId,
    title: 'Hammer-On & Pull-Off',
    description:
        'Spiele zwei Töne mit nur einem Anschlag: Hammer-On (drauf) und Pull-Off (runter).',
    instructions: [
      'Hammer-On: Schlage einen Ton an, "hämmere" einen Finger zwei Bünde höher.',
      'Pull-Off: Greife zwei Töne, schlage an, ziehe den höheren Finger weg.',
      'Beide Techniken sparen Anschläge und klingen flüssiger.',
      'Übe Hammer-On + Pull-Off als Trill (5h7p5h7p) auf der G-Saite.',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-6-1',
        lessonId: 'lesson-8-6',
        type: ExerciseType.singleNote,
        instructions: 'Spiele 8 Hammer-On/Pull-Off-Trills auf G-Saite Bund 5-7.',
        targetNoteOrChord: 'C4',
        bpm: 70,
        repetitionsRequired: 8,
        accuracyThreshold: 0.72,
        order: 1,
      ),
    ],
    xpReward: 180,
    difficulty: 6,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.overdrive,
    order: 6,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-8-7',
    moduleId: _moduleId,
    title: 'Slides',
    description:
        'Gleite von einem Ton zum anderen — Slides geben Soli Schwung und Drama.',
    instructions: [
      'Greife einen Ton, schlage an.',
      'Halte den Druck und gleite zu einem höheren oder tieferen Bund.',
      'Wichtig: ohne abzusetzen.',
      'Übe Slide von Bund 5 nach Bund 7 auf der G-Saite.',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-7-1',
        lessonId: 'lesson-8-7',
        type: ExerciseType.singleNote,
        instructions: 'Spiele 10 saubere Slides von Bund 5 nach 7 und zurück.',
        targetNoteOrChord: 'C4',
        bpm: 70,
        repetitionsRequired: 10,
        accuracyThreshold: 0.72,
        order: 1,
      ),
    ],
    xpReward: 160,
    difficulty: 6,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.overdrive,
    order: 7,
    estimatedMinutes: 10,
  ),
  Lesson(
    id: 'lesson-8-8',
    moduleId: _moduleId,
    title: '5 klassische Licks',
    description:
        'Fünf Licks aus der Moll-Pentatonik, die jeder Rock-Gitarrist kennt.',
    instructions: [
      'Lick 1: 5-7 auf G, dann 5-8 auf B (Albert-King-Lick).',
      'Lick 2: 7b9 auf G mit Vibrato (B.B.-King-Style).',
      'Lick 3: 5p7p5 auf B, dann 7-5 auf G.',
      'Lick 4: 8-5 auf B, dann 7-5 auf G — fließend.',
      'Lick 5: 5h7-5 auf G, dann 8-5 auf D.',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-8-1',
        lessonId: 'lesson-8-8',
        type: ExerciseType.scale,
        instructions: 'Spiele alle 5 Licks nacheinander, 3 Durchgänge.',
        targetNoteOrChord: 'A,C,D,E,G',
        bpm: 80,
        repetitionsRequired: 3,
        accuracyThreshold: 0.74,
        timeoutSeconds: 120,
        order: 1,
      ),
    ],
    xpReward: 240,
    difficulty: 6,
    targetAccuracy: 0.74,
    presetRequired: GuitarPreset.overdrive,
    scaleIds: const ['Am-pent-pos1'],
    order: 8,
    estimatedMinutes: 18,
  ),
  Lesson(
    id: 'lesson-8-9',
    moduleId: _moduleId,
    title: 'Freestyle-Solo',
    description:
        'Kombiniere alles, was du gelernt hast: Pentatonik, Bending, Vibrato, Hammer-On, Pull-Off, Slides.',
    instructions: [
      'Höre den Backing Track durch.',
      'Spiele 60 Sekunden frei in der A-Moll-Pentatonik.',
      'Setze mindestens eine Bending, ein Vibrato und einen Slide ein.',
      'Hab Spaß — es gibt kein "richtig" oder "falsch"!',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-9-1',
        lessonId: 'lesson-8-9',
        type: ExerciseType.scale,
        instructions: 'Improvisiere 60 Sekunden mit allen erlernten Techniken.',
        targetNoteOrChord: 'A,C,D,E,G',
        bpm: 90,
        repetitionsRequired: 1,
        accuracyThreshold: 0.72,
        timeoutSeconds: 90,
        order: 1,
      ),
    ],
    xpReward: 220,
    difficulty: 6,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.overdrive,
    scaleIds: const ['Am-pent-pos1'],
    order: 9,
    estimatedMinutes: 14,
  ),
  Lesson(
    id: 'lesson-8-10',
    moduleId: _moduleId,
    title: 'Positionen 2-5 + DISTORTION',
    description:
        'Erweitere die Pentatonik auf das ganze Griffbrett und schalte den DISTORTION-Sound frei!',
    instructions: [
      'Position 2: ab 7. Bund tiefe E-Saite (G-Pentatonik im A-Moll-Kontext).',
      'Position 3: ab 9. Bund.',
      'Position 4: ab 12. Bund.',
      'Position 5: ab 14./15. Bund — schließt den Kreis.',
      'Aktiviere das DISTORTION-Preset und höre den Unterschied!',
    ],
    exercises: [
      Exercise(
        id: 'ex-8-10-1',
        lessonId: 'lesson-8-10',
        type: ExerciseType.scale,
        instructions: 'Spiele alle 5 Positionen nacheinander auf und ab.',
        targetNoteOrChord: 'A,C,D,E,G',
        bpm: 80,
        repetitionsRequired: 1,
        accuracyThreshold: 0.72,
        timeoutSeconds: 180,
        order: 1,
      ),
    ],
    xpReward: 300,
    difficulty: 7,
    targetAccuracy: 0.72,
    presetRequired: GuitarPreset.distortion,
    scaleIds: const ['Am-pent-pos1', 'Am-pent-pos2', 'Am-pent-pos3', 'Am-pent-pos4', 'Am-pent-pos5'],
    order: 10,
    estimatedMinutes: 22,
  ),
];

final Module module8 = Module(
  id: _moduleId,
  moduleNumber: 8,
  title: 'Pentatonik & Solo-Basics',
  description:
      'Lerne die Moll-Pentatonik und alle wichtigen Solo-Techniken — und schalte den Distortion-Sound frei.',
  weekRange: 'Woche 15-18',
  presetRequired: GuitarPreset.overdrive,
  difficulty: 6,
  isLocked: true,
  unlockedPresets: const ['distortion'],
  learningGoals:
      'Moll-Pentatonik, Bending, Vibrato, Hammer-On, Pull-Off, Slides, klassische Licks, 5 Positionen, Distortion freischalten.',
  lessons: module8Lessons,
);
