import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import 'package:enya_gitarre_learn/app/theme/colors.dart';

class SongData {
  final String id;
  final String title;
  final String artist;
  final int difficulty;
  final String genre;
  final List<String> chords;
  final String lessonRef;
  final int bpm;
  final String tuning;

  const SongData({
    required this.id,
    required this.title,
    required this.artist,
    required this.difficulty,
    required this.genre,
    required this.chords,
    required this.lessonRef,
    required this.bpm,
    this.tuning = 'Standard',
  });
}

const List<SongData> kSongs = [
  // ── Rock ──────────────────────────────────────────────────────────────────
  SongData(
    id: 'smoke-on-the-water',
    title: 'Smoke on the Water',
    artist: 'Deep Purple',
    difficulty: 1,
    genre: 'Rock',
    chords: ['G5', 'A5', 'C5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'seven-nation-army',
    title: 'Seven Nation Army',
    artist: 'The White Stripes',
    difficulty: 1,
    genre: 'Rock',
    chords: ['E5', 'G5', 'D5', 'C5', 'B5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 124,
  ),
  SongData(
    id: 'wild-thing',
    title: 'Wild Thing',
    artist: 'The Troggs',
    difficulty: 1,
    genre: 'Rock',
    chords: ['A', 'D', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),
  SongData(
    id: 'johnny-b-goode',
    title: 'Johnny B. Goode',
    artist: 'Chuck Berry',
    difficulty: 1,
    genre: 'Rock',
    chords: ['A7', 'D7', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 168,
  ),
  SongData(
    id: 'you-really-got-me',
    title: 'You Really Got Me',
    artist: 'The Kinks',
    difficulty: 2,
    genre: 'Rock',
    chords: ['F5', 'G5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 136,
  ),
  SongData(
    id: 'creep',
    title: 'Creep',
    artist: 'Radiohead',
    difficulty: 2,
    genre: 'Rock',
    chords: ['G', 'B', 'C', 'Cm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 92,
  ),
  SongData(
    id: 'whole-lotta-love',
    title: 'Whole Lotta Love',
    artist: 'Led Zeppelin',
    difficulty: 2,
    genre: 'Rock',
    chords: ['E5', 'D5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 90,
  ),
  SongData(
    id: 'come-as-you-are',
    title: 'Come as You Are',
    artist: 'Nirvana',
    difficulty: 2,
    genre: 'Rock',
    chords: ['Em', 'Am', 'C', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 120,
  ),
  SongData(
    id: 'back-in-black',
    title: 'Back in Black',
    artist: 'AC/DC',
    difficulty: 2,
    genre: 'Rock',
    chords: ['E5', 'D5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 94,
  ),
  SongData(
    id: 'all-right-now',
    title: 'All Right Now',
    artist: 'Free',
    difficulty: 2,
    genre: 'Rock',
    chords: ['A', 'D', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 124,
  ),
  SongData(
    id: 'born-to-be-wild',
    title: 'Born to Be Wild',
    artist: 'Steppenwolf',
    difficulty: 2,
    genre: 'Rock',
    chords: ['E5', 'D5', 'G5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 144,
  ),
  SongData(
    id: 'smells-like-teen-spirit',
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    difficulty: 2,
    genre: 'Rock',
    chords: ['F5', 'A#5', 'G#5', 'C#5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 116,
  ),
  SongData(
    id: 'highway-to-hell',
    title: 'Highway to Hell',
    artist: 'AC/DC',
    difficulty: 2,
    genre: 'Rock',
    chords: ['A', 'D', 'G', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 116,
  ),
  SongData(
    id: 'brown-sugar',
    title: 'Brown Sugar',
    artist: 'The Rolling Stones',
    difficulty: 3,
    genre: 'Rock',
    chords: ['G', 'C', 'D', 'Bb'],
    lessonRef: 'module_1/lesson_1',
    bpm: 152,
  ),
  SongData(
    id: 'sympathy-for-the-devil',
    title: 'Sympathy for the Devil',
    artist: 'The Rolling Stones',
    difficulty: 3,
    genre: 'Rock',
    chords: ['E', 'D', 'A', 'B'],
    lessonRef: 'module_1/lesson_1',
    bpm: 128,
  ),
  SongData(
    id: 'layla',
    title: 'Layla',
    artist: 'Derek & the Dominos',
    difficulty: 3,
    genre: 'Rock',
    chords: ['Dm', 'Bb', 'C', 'Am'],
    lessonRef: 'module_1/lesson_1',
    bpm: 116,
  ),
  SongData(
    id: 'sunshine-of-your-love',
    title: 'Sunshine of Your Love',
    artist: 'Cream',
    difficulty: 3,
    genre: 'Rock',
    chords: ['D5', 'C5', 'A5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'paint-it-black',
    title: 'Paint It Black',
    artist: 'The Rolling Stones',
    difficulty: 3,
    genre: 'Rock',
    chords: ['Em', 'B7', 'G', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 160,
  ),
  SongData(
    id: 'black-dog',
    title: 'Black Dog',
    artist: 'Led Zeppelin',
    difficulty: 3,
    genre: 'Rock',
    chords: ['A5', 'D5', 'E5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 166,
  ),
  SongData(
    id: 'stairway-to-heaven',
    title: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    difficulty: 3,
    genre: 'Rock',
    chords: ['Am', 'G', 'F', 'C', 'D', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 82,
  ),

  // ── Pop ───────────────────────────────────────────────────────────────────
  SongData(
    id: 'let-her-go',
    title: 'Let Her Go',
    artist: 'Passenger',
    difficulty: 1,
    genre: 'Pop',
    chords: ['C', 'G', 'Am', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 74,
  ),
  SongData(
    id: 'someone-like-you',
    title: 'Someone Like You',
    artist: 'Adele',
    difficulty: 1,
    genre: 'Pop',
    chords: ['A', 'E', 'F#m', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 68,
  ),
  SongData(
    id: 'stand-by-me',
    title: 'Stand by Me',
    artist: 'Ben E. King',
    difficulty: 1,
    genre: 'Pop',
    chords: ['A', 'F#m', 'D', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'wonderful-tonight',
    title: 'Wonderful Tonight',
    artist: 'Eric Clapton',
    difficulty: 1,
    genre: 'Pop',
    chords: ['G', 'D', 'C', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'shape-of-you',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    difficulty: 1,
    genre: 'Pop',
    chords: ['C#m', 'F#m', 'A', 'B'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'perfect',
    title: 'Perfect',
    artist: 'Ed Sheeran',
    difficulty: 1,
    genre: 'Pop',
    chords: ['G', 'Em', 'C', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 95,
  ),
  SongData(
    id: 'use-somebody',
    title: 'Use Somebody',
    artist: 'Kings of Leon',
    difficulty: 2,
    genre: 'Pop',
    chords: ['C', 'F', 'Am', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 136,
  ),
  SongData(
    id: 'dont-look-back-in-anger',
    title: "Don't Look Back in Anger",
    artist: 'Oasis',
    difficulty: 2,
    genre: 'Pop',
    chords: ['C', 'G', 'Am', 'E', 'F', 'Fm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 68,
  ),
  SongData(
    id: 'wonderwall',
    title: 'Wonderwall',
    artist: 'Oasis',
    difficulty: 2,
    genre: 'Pop',
    chords: ['Em7', 'G', 'Dsus4', 'A7sus4', 'Cadd9'],
    lessonRef: 'module_1/lesson_1',
    bpm: 87,
  ),
  SongData(
    id: 'yellow',
    title: 'Yellow',
    artist: 'Coldplay',
    difficulty: 2,
    genre: 'Pop',
    chords: ['B', 'F#', 'E', 'Bbm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 87,
  ),
  SongData(
    id: 'lucky',
    title: 'Lucky',
    artist: 'Jason Mraz',
    difficulty: 2,
    genre: 'Pop',
    chords: ['G', 'D', 'Em', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 136,
  ),
  SongData(
    id: 'angels',
    title: 'Angels',
    artist: 'Robbie Williams',
    difficulty: 2,
    genre: 'Pop',
    chords: ['D', 'A', 'Bm', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'cant-help-falling-in-love',
    title: "Can't Help Falling in Love",
    artist: 'Elvis Presley',
    difficulty: 2,
    genre: 'Pop',
    chords: ['C', 'Em', 'Am', 'F', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 68,
  ),
  SongData(
    id: 'fix-you',
    title: 'Fix You',
    artist: 'Coldplay',
    difficulty: 2,
    genre: 'Pop',
    chords: ['C', 'Em', 'Am', 'F', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 69,
  ),
  SongData(
    id: 'take-me-to-church',
    title: 'Take Me to Church',
    artist: 'Hozier',
    difficulty: 2,
    genre: 'Pop',
    chords: ['Am', 'F', 'C', 'G', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 130,
  ),
  SongData(
    id: 'hotel-california',
    title: 'Hotel California',
    artist: 'Eagles',
    difficulty: 3,
    genre: 'Pop',
    chords: ['Am', 'E7', 'G', 'D', 'F', 'C', 'Dm', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 75,
  ),
  SongData(
    id: 'africa',
    title: 'Africa',
    artist: 'Toto',
    difficulty: 3,
    genre: 'Pop',
    chords: ['F#m', 'D', 'A', 'E', 'Bm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 92,
  ),
  SongData(
    id: 'fast-car',
    title: 'Fast Car',
    artist: 'Tracy Chapman',
    difficulty: 3,
    genre: 'Pop',
    chords: ['C', 'G', 'Am', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 102,
  ),
  SongData(
    id: 'more-than-words',
    title: 'More Than Words',
    artist: 'Extreme',
    difficulty: 3,
    genre: 'Pop',
    chords: ['G', 'Cadd9', 'Am7', 'C', 'D', 'Em', 'Dsus4'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'tears-in-heaven',
    title: 'Tears in Heaven',
    artist: 'Eric Clapton',
    difficulty: 3,
    genre: 'Pop',
    chords: ['A', 'E', 'F#m', 'C#', 'D', 'G#m', 'Bm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 80,
  ),

  // ── Blues ─────────────────────────────────────────────────────────────────
  SongData(
    id: 'sweet-home-chicago',
    title: 'Sweet Home Chicago',
    artist: 'Robert Johnson',
    difficulty: 1,
    genre: 'Blues',
    chords: ['E7', 'A7', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'red-house',
    title: 'Red House',
    artist: 'Jimi Hendrix',
    difficulty: 1,
    genre: 'Blues',
    chords: ['B7', 'E7', 'F#7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 52,
  ),
  SongData(
    id: 'the-thrill-is-gone',
    title: 'The Thrill Is Gone',
    artist: 'B.B. King',
    difficulty: 1,
    genre: 'Blues',
    chords: ['Bm', 'Em', 'G', 'F#7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 60,
  ),
  SongData(
    id: 'pride-and-joy',
    title: 'Pride and Joy',
    artist: 'Stevie Ray Vaughan',
    difficulty: 2,
    genre: 'Blues',
    chords: ['E7', 'A7', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 188,
  ),
  SongData(
    id: 'crossroad-blues',
    title: 'Cross Road Blues',
    artist: 'Robert Johnson',
    difficulty: 2,
    genre: 'Blues',
    chords: ['A7', 'D7', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 84,
  ),
  SongData(
    id: 'hoodoo-man-blues',
    title: 'Hoodoo Man Blues',
    artist: 'Junior Wells',
    difficulty: 2,
    genre: 'Blues',
    chords: ['E7', 'A7', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 80,
  ),
  SongData(
    id: 'stormy-monday',
    title: 'Stormy Monday',
    artist: 'T-Bone Walker',
    difficulty: 2,
    genre: 'Blues',
    chords: ['G7', 'Cm7', 'Am7', 'D7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 62,
  ),
  SongData(
    id: 'key-to-the-highway',
    title: 'Key to the Highway',
    artist: 'Big Bill Broonzy',
    difficulty: 2,
    genre: 'Blues',
    chords: ['A', 'D', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 116,
  ),
  SongData(
    id: 'mannish-boy',
    title: 'Mannish Boy',
    artist: 'Muddy Waters',
    difficulty: 2,
    genre: 'Blues',
    chords: ['E7', 'A7', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),
  SongData(
    id: 'texas-flood',
    title: 'Texas Flood',
    artist: 'Stevie Ray Vaughan',
    difficulty: 2,
    genre: 'Blues',
    chords: ['G7', 'C7', 'D7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 58,
  ),
  SongData(
    id: 'born-under-a-bad-sign',
    title: 'Born Under a Bad Sign',
    artist: 'Albert King',
    difficulty: 2,
    genre: 'Blues',
    chords: ['C#7', 'F#7', 'G#7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 80,
  ),
  SongData(
    id: 'hoochie-coochie-man',
    title: 'Hoochie Coochie Man',
    artist: 'Muddy Waters',
    difficulty: 2,
    genre: 'Blues',
    chords: ['A7', 'D7', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 92,
  ),
  SongData(
    id: 'still-got-the-blues',
    title: 'Still Got the Blues',
    artist: 'Gary Moore',
    difficulty: 3,
    genre: 'Blues',
    chords: ['Am', 'Dm', 'E7', 'G', 'C', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 68,
  ),
  SongData(
    id: 'little-wing',
    title: 'Little Wing',
    artist: 'Jimi Hendrix',
    difficulty: 3,
    genre: 'Blues',
    chords: ['Em', 'G', 'Am', 'Em7', 'Bm', 'Bb', 'Am7', 'C', 'D', 'F', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 68,
  ),
  SongData(
    id: 'since-i-ve-been-loving-you',
    title: "Since I've Been Loving You",
    artist: 'Led Zeppelin',
    difficulty: 3,
    genre: 'Blues',
    chords: ['Cm', 'Fm', 'Bb7', 'Ab', 'G7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 60,
  ),
  SongData(
    id: 'whipping-post',
    title: 'Whipping Post',
    artist: 'Allman Brothers Band',
    difficulty: 3,
    genre: 'Blues',
    chords: ['Am', 'G', 'F', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 82,
  ),
  SongData(
    id: 'comfortably-numb',
    title: 'Comfortably Numb',
    artist: 'Pink Floyd',
    difficulty: 3,
    genre: 'Blues',
    chords: ['Bm', 'A', 'G', 'Em', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 62,
  ),
  SongData(
    id: 'love-struck-baby',
    title: 'Love Struck Baby',
    artist: 'Stevie Ray Vaughan',
    difficulty: 3,
    genre: 'Blues',
    chords: ['E7', 'A7', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 200,
  ),
  SongData(
    id: 'all-your-love',
    title: 'All Your Love',
    artist: 'Otis Rush',
    difficulty: 3,
    genre: 'Blues',
    chords: ['Am', 'Dm', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 132,
  ),
  SongData(
    id: 'smoking-gun',
    title: 'Smoking Gun',
    artist: 'Robert Cray',
    difficulty: 3,
    genre: 'Blues',
    chords: ['Cm7', 'Fm7', 'G7', 'Ab'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),

  // ── Metal ─────────────────────────────────────────────────────────────────
  SongData(
    id: 'iron-man',
    title: 'Iron Man',
    artist: 'Black Sabbath',
    difficulty: 1,
    genre: 'Metal',
    chords: ['B5', 'D5', 'E5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'paranoid',
    title: 'Paranoid',
    artist: 'Black Sabbath',
    difficulty: 1,
    genre: 'Metal',
    chords: ['E5', 'D5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 164,
  ),
  SongData(
    id: 'breaking-the-law',
    title: 'Breaking the Law',
    artist: 'Judas Priest',
    difficulty: 1,
    genre: 'Metal',
    chords: ['E5', 'G5', 'A5', 'C5', 'D5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 152,
  ),
  SongData(
    id: 'highway-star',
    title: 'Highway Star',
    artist: 'Deep Purple',
    difficulty: 2,
    genre: 'Metal',
    chords: ['G5', 'C5', 'D5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 170,
  ),
  SongData(
    id: 'ace-of-spades',
    title: 'Ace of Spades',
    artist: 'Motörhead',
    difficulty: 2,
    genre: 'Metal',
    chords: ['Am', 'G5', 'F5', 'E5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 220,
  ),
  SongData(
    id: 'enter-sandman',
    title: 'Enter Sandman',
    artist: 'Metallica',
    difficulty: 2,
    genre: 'Metal',
    chords: ['E5', 'G5', 'A5', 'F#5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 122,
  ),
  SongData(
    id: 'master-of-puppets',
    title: 'Master of Puppets',
    artist: 'Metallica',
    difficulty: 2,
    genre: 'Metal',
    chords: ['Em', 'F5', 'E5', 'Am'],
    lessonRef: 'module_1/lesson_1',
    bpm: 212,
  ),
  SongData(
    id: 'for-whom-the-bell-tolls',
    title: 'For Whom the Bell Tolls',
    artist: 'Metallica',
    difficulty: 2,
    genre: 'Metal',
    chords: ['F5', 'Ab5', 'Bb5', 'C5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'war-pigs',
    title: 'War Pigs',
    artist: 'Black Sabbath',
    difficulty: 2,
    genre: 'Metal',
    chords: ['D5', 'E5', 'G5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 72,
  ),
  SongData(
    id: 'holy-diver',
    title: 'Holy Diver',
    artist: 'Dio',
    difficulty: 2,
    genre: 'Metal',
    chords: ['Dm', 'Am', 'C', 'Bb', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 88,
  ),
  SongData(
    id: 'crazy-train',
    title: 'Crazy Train',
    artist: 'Ozzy Osbourne',
    difficulty: 2,
    genre: 'Metal',
    chords: ['A5', 'F#5', 'D5', 'E5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 138,
  ),
  SongData(
    id: 'you-ve-got-another-thing-coming',
    title: "You've Got Another Thing Comin'",
    artist: 'Judas Priest',
    difficulty: 2,
    genre: 'Metal',
    chords: ['E5', 'A5', 'B5', 'D5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 152,
  ),
  SongData(
    id: 'fade-to-black',
    title: 'Fade to Black',
    artist: 'Metallica',
    difficulty: 3,
    genre: 'Metal',
    chords: ['Am', 'E', 'D', 'G', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'eruption',
    title: 'Eruption',
    artist: 'Van Halen',
    difficulty: 3,
    genre: 'Metal',
    chords: ['D5', 'C5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 136,
  ),
  SongData(
    id: 'raining-blood',
    title: 'Raining Blood',
    artist: 'Slayer',
    difficulty: 3,
    genre: 'Metal',
    chords: ['Em', 'D#5', 'D5', 'C#5', 'C5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 200,
    tuning: 'Drop D',
  ),
  SongData(
    id: 'battery',
    title: 'Battery',
    artist: 'Metallica',
    difficulty: 3,
    genre: 'Metal',
    chords: ['C5', 'B5', 'Bb5', 'A5', 'E5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 200,
  ),
  SongData(
    id: 'nothing-else-matters',
    title: 'Nothing Else Matters',
    artist: 'Metallica',
    difficulty: 3,
    genre: 'Metal',
    chords: ['Em', 'Am', 'C', 'D', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 69,
  ),
  SongData(
    id: 'through-the-fire-and-flames',
    title: 'Through the Fire and Flames',
    artist: 'DragonForce',
    difficulty: 3,
    genre: 'Metal',
    chords: ['E5', 'A5', 'B5', 'C#5', 'G#5', 'F#5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 200,
  ),
  SongData(
    id: 'zero-signal',
    title: 'Zero Signal',
    artist: 'Fear Factory',
    difficulty: 3,
    genre: 'Metal',
    chords: ['D5', 'C5', 'Bb5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 148,
    tuning: 'Drop D',
  ),
  SongData(
    id: 'cemetary-gates',
    title: 'Cemetery Gates',
    artist: 'Pantera',
    difficulty: 3,
    genre: 'Metal',
    chords: ['Em', 'Am', 'D', 'G', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),

  // ── Folk / Acoustic ───────────────────────────────────────────────────────
  SongData(
    id: 'knockin-on-heavens-door',
    title: "Knockin' on Heaven's Door",
    artist: 'Bob Dylan',
    difficulty: 1,
    genre: 'Folk / Acoustic',
    chords: ['G', 'D', 'Am', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 68,
  ),
  SongData(
    id: 'blowin-in-the-wind',
    title: 'Blowin\' in the Wind',
    artist: 'Bob Dylan',
    difficulty: 1,
    genre: 'Folk / Acoustic',
    chords: ['D', 'G', 'A'],
    lessonRef: 'module_1/lesson_1',
    bpm: 88,
  ),
  SongData(
    id: 'horse-with-no-name',
    title: 'A Horse with No Name',
    artist: 'America',
    difficulty: 1,
    genre: 'Folk / Acoustic',
    chords: ['Em', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 78,
  ),
  SongData(
    id: 'dust-in-the-wind',
    title: 'Dust in the Wind',
    artist: 'Kansas',
    difficulty: 1,
    genre: 'Folk / Acoustic',
    chords: ['C', 'Am', 'G', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'leaving-on-a-jet-plane',
    title: 'Leaving on a Jet Plane',
    artist: 'John Denver',
    difficulty: 1,
    genre: 'Folk / Acoustic',
    chords: ['G', 'C', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),
  SongData(
    id: 'country-roads',
    title: 'Take Me Home, Country Roads',
    artist: 'John Denver',
    difficulty: 1,
    genre: 'Folk / Acoustic',
    chords: ['G', 'Em', 'D', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 84,
  ),
  SongData(
    id: 'the-sound-of-silence',
    title: 'The Sound of Silence',
    artist: 'Simon & Garfunkel',
    difficulty: 2,
    genre: 'Folk / Acoustic',
    chords: ['Am', 'G', 'F', 'C', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'scarborough-fair',
    title: 'Scarborough Fair',
    artist: 'Simon & Garfunkel',
    difficulty: 2,
    genre: 'Folk / Acoustic',
    chords: ['Am', 'G', 'C', 'D', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 88,
  ),
  SongData(
    id: 'the-boxer',
    title: 'The Boxer',
    artist: 'Simon & Garfunkel',
    difficulty: 2,
    genre: 'Folk / Acoustic',
    chords: ['C', 'Am', 'G', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 80,
  ),
  SongData(
    id: 'norwegianwood',
    title: 'Norwegian Wood',
    artist: 'The Beatles',
    difficulty: 2,
    genre: 'Folk / Acoustic',
    chords: ['D', 'C', 'G', 'Dm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 64,
  ),
  SongData(
    id: 'blackbird',
    title: 'Blackbird',
    artist: 'The Beatles',
    difficulty: 2,
    genre: 'Folk / Acoustic',
    chords: ['G', 'Am7', 'C', 'G7', 'F', 'Em', 'Dm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 94,
  ),
  SongData(
    id: 'fire-and-rain',
    title: 'Fire and Rain',
    artist: 'James Taylor',
    difficulty: 2,
    genre: 'Folk / Acoustic',
    chords: ['A', 'D', 'G', 'Bm', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 78,
  ),
  SongData(
    id: 'the-house-of-the-rising-sun',
    title: 'House of the Rising Sun',
    artist: 'The Animals',
    difficulty: 2,
    genre: 'Folk / Acoustic',
    chords: ['Am', 'C', 'D', 'F', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'hallelujah',
    title: 'Hallelujah',
    artist: 'Leonard Cohen',
    difficulty: 2,
    genre: 'Folk / Acoustic',
    chords: ['C', 'Am', 'F', 'G', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 64,
  ),
  SongData(
    id: 'wish-you-were-here',
    title: 'Wish You Were Here',
    artist: 'Pink Floyd',
    difficulty: 2,
    genre: 'Folk / Acoustic',
    chords: ['Em7', 'G', 'A', 'C', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 63,
  ),
  SongData(
    id: 'big-yellow-taxi',
    title: 'Big Yellow Taxi',
    artist: 'Joni Mitchell',
    difficulty: 3,
    genre: 'Folk / Acoustic',
    chords: ['A', 'D', 'E', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 130,
  ),
  SongData(
    id: 'both-sides-now',
    title: 'Both Sides Now',
    artist: 'Joni Mitchell',
    difficulty: 3,
    genre: 'Folk / Acoustic',
    chords: ['G', 'D', 'Em', 'C', 'Am'],
    lessonRef: 'module_1/lesson_1',
    bpm: 78,
  ),
  SongData(
    id: 'tangerine',
    title: 'Tangerine',
    artist: 'Led Zeppelin',
    difficulty: 3,
    genre: 'Folk / Acoustic',
    chords: ['G', 'D', 'A', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 68,
    tuning: 'Open G',
  ),
  SongData(
    id: 'bron-y-aur-stomp',
    title: 'Bron-Y-Aur Stomp',
    artist: 'Led Zeppelin',
    difficulty: 3,
    genre: 'Folk / Acoustic',
    chords: ['C', 'F', 'G', 'Am', 'Dm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 160,
  ),
  SongData(
    id: 'the-needle-and-the-damage-done',
    title: 'The Needle and the Damage Done',
    artist: 'Neil Young',
    difficulty: 3,
    genre: 'Folk / Acoustic',
    chords: ['D', 'C', 'G', 'Am', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 88,
  ),

  // ── Klassik (fingerstyle) ─────────────────────────────────────────────────
  SongData(
    id: 'romanza',
    title: 'Romanza (Spanish Romance)',
    artist: 'Anon.',
    difficulty: 1,
    genre: 'Klassik',
    chords: ['Em', 'B7', 'Am', 'C', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'ode-an-die-freude',
    title: 'Ode an die Freude',
    artist: 'Beethoven',
    difficulty: 1,
    genre: 'Klassik',
    chords: ['E', 'A', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'greensleeves',
    title: 'Greensleeves',
    artist: 'Traditional',
    difficulty: 1,
    genre: 'Klassik',
    chords: ['Am', 'G', 'E', 'C', 'F', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'minuet-in-g',
    title: 'Minuet in G',
    artist: 'Bach / Petzold',
    difficulty: 1,
    genre: 'Klassik',
    chords: ['G', 'C', 'D', 'Em', 'Am'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'canon-in-d',
    title: 'Canon in D',
    artist: 'Pachelbel',
    difficulty: 2,
    genre: 'Klassik',
    chords: ['D', 'A', 'Bm', 'F#m', 'G', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 66,
  ),
  SongData(
    id: 'fur-elise',
    title: 'Für Elise',
    artist: 'Beethoven',
    difficulty: 2,
    genre: 'Klassik',
    chords: ['Am', 'E7', 'F', 'C', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 92,
  ),
  SongData(
    id: 'jesu-joy-of-mans-desiring',
    title: 'Jesu, Joy of Man\'s Desiring',
    artist: 'Bach',
    difficulty: 2,
    genre: 'Klassik',
    chords: ['G', 'Em', 'Am', 'D', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 78,
  ),
  SongData(
    id: 'bourree-e-minor',
    title: 'Bourrée in E minor',
    artist: 'Bach',
    difficulty: 2,
    genre: 'Klassik',
    chords: ['Em', 'Am', 'B7', 'D', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 120,
  ),
  SongData(
    id: 'lagrima',
    title: 'Lágrima',
    artist: 'Francisco Tárrega',
    difficulty: 2,
    genre: 'Klassik',
    chords: ['E', 'B7', 'Am', 'C', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 60,
  ),
  SongData(
    id: 'adelita',
    title: 'Adelita',
    artist: 'Francisco Tárrega',
    difficulty: 2,
    genre: 'Klassik',
    chords: ['D', 'A7', 'Gm', 'Dm', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),
  SongData(
    id: 'asturias',
    title: 'Asturias (Leyenda)',
    artist: 'Isaac Albéniz',
    difficulty: 3,
    genre: 'Klassik',
    chords: ['Am', 'E7', 'G', 'Dm', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 116,
  ),
  SongData(
    id: 'recuerdos-de-la-alhambra',
    title: 'Recuerdos de la Alhambra',
    artist: 'Francisco Tárrega',
    difficulty: 3,
    genre: 'Klassik',
    chords: ['Am', 'E7', 'Dm', 'G', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 80,
  ),
  SongData(
    id: 'capricho-arabe',
    title: 'Capricho Árabe',
    artist: 'Francisco Tárrega',
    difficulty: 3,
    genre: 'Klassik',
    chords: ['Dm', 'A7', 'Gm', 'C', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'variations-on-a-theme-by-handel',
    title: 'Variations on a Theme by Handel',
    artist: 'Mauro Giuliani',
    difficulty: 3,
    genre: 'Klassik',
    chords: ['A', 'D', 'E7', 'Bm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 88,
  ),
  SongData(
    id: 'andantino',
    title: 'Andantino in C',
    artist: 'Matteo Carcassi',
    difficulty: 2,
    genre: 'Klassik',
    chords: ['C', 'G7', 'Am', 'F', 'Dm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 84,
  ),
  SongData(
    id: 'prelude-in-d-minor',
    title: 'Prélude in D minor',
    artist: 'Heitor Villa-Lobos',
    difficulty: 3,
    genre: 'Klassik',
    chords: ['Dm', 'A7', 'Gm', 'C', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 60,
  ),
  SongData(
    id: 'malaguena',
    title: 'Malagueña',
    artist: 'Traditional / Ernesto Lecuona',
    difficulty: 3,
    genre: 'Klassik',
    chords: ['Am', 'E7', 'F', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 140,
  ),
  SongData(
    id: 'etude-op-35-no-22',
    title: 'Étude Op. 35 No. 22',
    artist: 'Fernando Sor',
    difficulty: 3,
    genre: 'Klassik',
    chords: ['G', 'D7', 'C', 'Em', 'Am'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'allegro-moderato',
    title: 'Allegro Moderato',
    artist: 'Fernando Carulli',
    difficulty: 2,
    genre: 'Klassik',
    chords: ['C', 'G7', 'F', 'Am', 'Dm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),
  SongData(
    id: 'estudio-in-e-major',
    title: 'Estudio in E major',
    artist: 'Leo Brouwer',
    difficulty: 3,
    genre: 'Klassik',
    chords: ['E', 'A', 'B7', 'C#m'],
    lessonRef: 'module_1/lesson_1',
    bpm: 92,
  ),

  // ── Deutsch ───────────────────────────────────────────────────────────────
  SongData(
    id: 'sonne',
    title: 'Sonne',
    artist: 'Rammstein',
    difficulty: 1,
    genre: 'Deutsch',
    chords: ['E5', 'A5', 'D5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'ich-will',
    title: 'Ich will',
    artist: 'Rammstein',
    difficulty: 1,
    genre: 'Deutsch',
    chords: ['D5', 'C5', 'A5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 130,
  ),
  SongData(
    id: 'du-hast',
    title: 'Du hast',
    artist: 'Rammstein',
    difficulty: 1,
    genre: 'Deutsch',
    chords: ['E5', 'G5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 136,
  ),
  SongData(
    id: 'wind-of-change',
    title: 'Wind of Change',
    artist: 'Scorpions',
    difficulty: 1,
    genre: 'Deutsch',
    chords: ['C', 'G', 'Am', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 70,
  ),
  SongData(
    id: 'rock-you-like-a-hurricane',
    title: 'Rock You Like a Hurricane',
    artist: 'Scorpions',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['E5', 'G5', 'A5', 'C5', 'D5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 124,
  ),
  SongData(
    id: 'still-loving-you',
    title: 'Still Loving You',
    artist: 'Scorpions',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['Am', 'G', 'F', 'E', 'C', 'Dm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 66,
  ),
  SongData(
    id: 'stadtaffe',
    title: 'Stadtaffe',
    artist: 'Peter Fox',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['Am', 'G', 'C', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),
  SongData(
    id: 'schwarz-zu-blau',
    title: 'Schwarz zu Blau',
    artist: 'Peter Fox',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['Dm', 'Am', 'C', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 92,
  ),
  SongData(
    id: 'ein-kompliment',
    title: 'Ein Kompliment',
    artist: 'Sportfreunde Stiller',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['D', 'A', 'G', 'Bm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'hier-kommt-alex',
    title: 'Hier kommt Alex',
    artist: 'Die Toten Hosen',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['A', 'D', 'E', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 148,
  ),
  SongData(
    id: 'azzurro',
    title: 'Azzurro',
    artist: 'Rosenstolz',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['Am', 'F', 'C', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'perfekte-welle',
    title: 'Perfekte Welle',
    artist: 'Juli',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['D', 'Bm', 'G', 'A'],
    lessonRef: 'module_1/lesson_1',
    bpm: 138,
  ),
  SongData(
    id: 'nummer-eins',
    title: 'Wir sind alle gleich',
    artist: 'Die Ärzte',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['G', 'C', 'D', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 120,
  ),
  SongData(
    id: 'radio-gaga',
    title: 'Schrei nach Liebe',
    artist: 'Die Ärzte',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['D', 'A', 'Bm', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 176,
  ),
  SongData(
    id: 'durch-den-monsun',
    title: 'Durch den Monsun',
    artist: 'Tokio Hotel',
    difficulty: 2,
    genre: 'Deutsch',
    chords: ['Am', 'F', 'C', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 140,
  ),
  SongData(
    id: 'du-riechst-so-gut',
    title: 'Du riechst so gut',
    artist: 'Rammstein',
    difficulty: 3,
    genre: 'Deutsch',
    chords: ['E5', 'D5', 'A5', 'F5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 124,
  ),
  SongData(
    id: 'feuer-frei',
    title: 'Feuer frei!',
    artist: 'Rammstein',
    difficulty: 3,
    genre: 'Deutsch',
    chords: ['D5', 'C5', 'Bb5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 138,
  ),
  SongData(
    id: 'kein-zurueck',
    title: 'Kein Zurück',
    artist: 'Unheilig',
    difficulty: 3,
    genre: 'Deutsch',
    chords: ['Am', 'F', 'C', 'G', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 128,
  ),
  SongData(
    id: 'ich-und-ich-stark',
    title: 'Stark',
    artist: 'Ich + Ich',
    difficulty: 3,
    genre: 'Deutsch',
    chords: ['Am', 'G', 'F', 'C', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 130,
  ),
  SongData(
    id: 'engel',
    title: 'Engel',
    artist: 'Rammstein',
    difficulty: 3,
    genre: 'Deutsch',
    chords: ['Am', 'F', 'G', 'C', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 104,
  ),

  // ── Punk ──────────────────────────────────────────────────────────────────
  SongData(
    id: 'basket-case',
    title: 'Basket Case',
    artist: 'Green Day',
    difficulty: 1,
    genre: 'Punk',
    chords: ['Eb', 'Bb', 'C', 'G', 'Ab'],
    lessonRef: 'module_1/lesson_1',
    bpm: 174,
  ),
  SongData(
    id: 'when-i-come-around',
    title: 'When I Come Around',
    artist: 'Green Day',
    difficulty: 1,
    genre: 'Punk',
    chords: ['G', 'D', 'Em', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 108,
  ),
  SongData(
    id: 'american-idiot',
    title: 'American Idiot',
    artist: 'Green Day',
    difficulty: 1,
    genre: 'Punk',
    chords: ['A5', 'D5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 186,
  ),
  SongData(
    id: 'anarchy-in-the-uk',
    title: 'Anarchy in the U.K.',
    artist: 'Sex Pistols',
    difficulty: 1,
    genre: 'Punk',
    chords: ['A5', 'D5', 'E5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 200,
  ),
  SongData(
    id: 'should-i-stay-or-should-i-go',
    title: 'Should I Stay or Should I Go',
    artist: 'The Clash',
    difficulty: 1,
    genre: 'Punk',
    chords: ['D5', 'G5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'london-calling',
    title: 'London Calling',
    artist: 'The Clash',
    difficulty: 2,
    genre: 'Punk',
    chords: ['Em', 'Am', 'D', 'G', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 152,
  ),
  SongData(
    id: 'rockaway-beach',
    title: 'Rockaway Beach',
    artist: 'Ramones',
    difficulty: 2,
    genre: 'Punk',
    chords: ['D', 'A', 'G', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 176,
  ),
  SongData(
    id: 'blitzkrieg-bop',
    title: 'Blitzkrieg Bop',
    artist: 'Ramones',
    difficulty: 2,
    genre: 'Punk',
    chords: ['A', 'D', 'E', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 190,
  ),
  SongData(
    id: 'i-wanna-be-sedated',
    title: 'I Wanna Be Sedated',
    artist: 'Ramones',
    difficulty: 2,
    genre: 'Punk',
    chords: ['A', 'D', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 190,
  ),
  SongData(
    id: 'brain-stew',
    title: 'Brain Stew',
    artist: 'Green Day',
    difficulty: 2,
    genre: 'Punk',
    chords: ['A5', 'G#5', 'G5', 'F#5', 'F5', 'E5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'all-the-small-things',
    title: 'All the Small Things',
    artist: 'Blink-182',
    difficulty: 2,
    genre: 'Punk',
    chords: ['C', 'G', 'F', 'Bb'],
    lessonRef: 'module_1/lesson_1',
    bpm: 148,
  ),
  SongData(
    id: 'what-i-got',
    title: 'What I Got',
    artist: 'Sublime',
    difficulty: 2,
    genre: 'Punk',
    chords: ['D', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 92,
  ),
  SongData(
    id: 'pretty-fly-for-a-white-guy',
    title: 'Pretty Fly (For a White Guy)',
    artist: 'The Offspring',
    difficulty: 2,
    genre: 'Punk',
    chords: ['Bb', 'C5', 'F5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 190,
  ),
  SongData(
    id: 'self-esteem',
    title: 'Self Esteem',
    artist: 'The Offspring',
    difficulty: 2,
    genre: 'Punk',
    chords: ['Bb', 'F', 'G', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 104,
  ),
  SongData(
    id: 'holiday-green-day',
    title: 'Holiday',
    artist: 'Green Day',
    difficulty: 2,
    genre: 'Punk',
    chords: ['Fm', 'Db', 'Ab', 'Eb', 'Bb'],
    lessonRef: 'module_1/lesson_1',
    bpm: 148,
  ),
  SongData(
    id: 'bad-reputation',
    title: 'Bad Reputation',
    artist: 'Joan Jett',
    difficulty: 2,
    genre: 'Punk',
    chords: ['G', 'C', 'D', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 162,
  ),
  SongData(
    id: 'ever-fallen-in-love',
    title: 'Ever Fallen in Love',
    artist: 'Buzzcocks',
    difficulty: 3,
    genre: 'Punk',
    chords: ['E', 'A', 'B', 'C#m'],
    lessonRef: 'module_1/lesson_1',
    bpm: 136,
  ),
  SongData(
    id: 'common-people',
    title: 'Common People',
    artist: 'Pulp',
    difficulty: 3,
    genre: 'Punk',
    chords: ['G', 'C', 'D', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 130,
  ),
  SongData(
    id: 'sex-and-violence',
    title: 'Sex & Violence',
    artist: 'The Exploited',
    difficulty: 3,
    genre: 'Punk',
    chords: ['E5', 'A5', 'D5', 'G5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 200,
  ),
  SongData(
    id: 'in-the-city',
    title: 'In the City',
    artist: 'The Jam',
    difficulty: 3,
    genre: 'Punk',
    chords: ['A', 'D', 'E', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 172,
  ),

  // ── Reggae / Ska ──────────────────────────────────────────────────────────
  SongData(
    id: 'no-woman-no-cry',
    title: 'No Woman, No Cry',
    artist: 'Bob Marley',
    difficulty: 1,
    genre: 'Reggae / Ska',
    chords: ['C', 'G', 'Am', 'F'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'three-little-birds',
    title: 'Three Little Birds',
    artist: 'Bob Marley',
    difficulty: 1,
    genre: 'Reggae / Ska',
    chords: ['A', 'D', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'stir-it-up',
    title: 'Stir It Up',
    artist: 'Bob Marley',
    difficulty: 1,
    genre: 'Reggae / Ska',
    chords: ['A', 'D', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 80,
  ),
  SongData(
    id: 'buffalo-soldier',
    title: 'Buffalo Soldier',
    artist: 'Bob Marley',
    difficulty: 1,
    genre: 'Reggae / Ska',
    chords: ['G', 'C', 'D', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 108,
  ),
  SongData(
    id: 'redemption-song',
    title: 'Redemption Song',
    artist: 'Bob Marley',
    difficulty: 1,
    genre: 'Reggae / Ska',
    chords: ['G', 'C', 'Am', 'Em', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 75,
  ),
  SongData(
    id: 'one-love',
    title: 'One Love / People Get Ready',
    artist: 'Bob Marley',
    difficulty: 1,
    genre: 'Reggae / Ska',
    chords: ['A', 'D', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'is-this-love',
    title: 'Is This Love',
    artist: 'Bob Marley',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['G', 'C', 'Em', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 90,
  ),
  SongData(
    id: 'could-you-be-loved',
    title: 'Could You Be Loved',
    artist: 'Bob Marley',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['D', 'Bm', 'G', 'A'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'monkey-man',
    title: 'Monkey Man',
    artist: 'Toots & the Maytals',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['D', 'G', 'A', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 88,
  ),
  SongData(
    id: 'pressure-drop',
    title: 'Pressure Drop',
    artist: 'Toots & the Maytals',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['G', 'C', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),
  SongData(
    id: 'the-tide-is-high',
    title: 'The Tide Is High',
    artist: 'Blondie',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['A', 'D', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 92,
  ),
  SongData(
    id: 'ghost-town',
    title: 'Ghost Town',
    artist: 'The Specials',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['Dm', 'Am', 'Bb', 'A'],
    lessonRef: 'module_1/lesson_1',
    bpm: 110,
  ),
  SongData(
    id: 'a-message-to-you-rudy',
    title: 'A Message to You Rudy',
    artist: 'The Specials',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['F', 'Bb', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 132,
  ),
  SongData(
    id: 'gangsters',
    title: 'Gangsters',
    artist: 'The Specials',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['Am', 'F', 'G', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 118,
  ),
  SongData(
    id: 'one-step-beyond',
    title: 'One Step Beyond',
    artist: 'Madness',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['A', 'D', 'G', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 140,
  ),
  SongData(
    id: 'our-house',
    title: 'Our House',
    artist: 'Madness',
    difficulty: 2,
    genre: 'Reggae / Ska',
    chords: ['G', 'C', 'D', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 136,
  ),
  SongData(
    id: 'many-rivers-to-cross',
    title: 'Many Rivers to Cross',
    artist: 'Jimmy Cliff',
    difficulty: 3,
    genre: 'Reggae / Ska',
    chords: ['C', 'Am', 'G', 'F', 'Dm', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 74,
  ),
  SongData(
    id: 'rivers-of-babylon',
    title: 'Rivers of Babylon',
    artist: 'The Melodians',
    difficulty: 3,
    genre: 'Reggae / Ska',
    chords: ['D', 'G', 'A7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 88,
  ),
  SongData(
    id: 'concrete-jungle',
    title: 'Concrete Jungle',
    artist: 'Bob Marley',
    difficulty: 3,
    genre: 'Reggae / Ska',
    chords: ['Am', 'G', 'F', 'E', 'Dm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 92,
  ),
  SongData(
    id: 'the-harder-they-come',
    title: 'The Harder They Come',
    artist: 'Jimmy Cliff',
    difficulty: 3,
    genre: 'Reggae / Ska',
    chords: ['C', 'F', 'G', 'Am'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),

  // ── Country ───────────────────────────────────────────────────────────────
  SongData(
    id: 'jolene',
    title: 'Jolene',
    artist: 'Dolly Parton',
    difficulty: 1,
    genre: 'Country',
    chords: ['Am', 'C', 'G', 'Em'],
    lessonRef: 'module_1/lesson_1',
    bpm: 130,
  ),
  SongData(
    id: 'ring-of-fire',
    title: 'Ring of Fire',
    artist: 'Johnny Cash',
    difficulty: 1,
    genre: 'Country',
    chords: ['G', 'C', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 142,
  ),
  SongData(
    id: 'jackson',
    title: 'Jackson',
    artist: 'Johnny Cash & June Carter',
    difficulty: 1,
    genre: 'Country',
    chords: ['C', 'F', 'G7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 138,
  ),
  SongData(
    id: 'country-roads-denver',
    title: 'Take Me Home, Country Roads',
    artist: 'John Denver',
    difficulty: 1,
    genre: 'Country',
    chords: ['G', 'Em', 'D', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 84,
  ),
  SongData(
    id: 'i-walk-the-line',
    title: 'I Walk the Line',
    artist: 'Johnny Cash',
    difficulty: 1,
    genre: 'Country',
    chords: ['C', 'F', 'G7', 'D7', 'A7', 'E7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 112,
  ),
  SongData(
    id: 'wagon-wheel',
    title: 'Wagon Wheel',
    artist: 'Old Crow Medicine Show / Darius Rucker',
    difficulty: 1,
    genre: 'Country',
    chords: ['G', 'D', 'Em', 'C'],
    lessonRef: 'module_1/lesson_1',
    bpm: 100,
  ),
  SongData(
    id: 'friends-in-low-places',
    title: 'Friends in Low Places',
    artist: 'Garth Brooks',
    difficulty: 2,
    genre: 'Country',
    chords: ['G', 'A', 'D', 'Em', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 96,
  ),
  SongData(
    id: 'tennessee-whiskey',
    title: 'Tennessee Whiskey',
    artist: 'Chris Stapleton',
    difficulty: 2,
    genre: 'Country',
    chords: ['A', 'Bm', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 64,
  ),
  SongData(
    id: 'need-you-now',
    title: 'Need You Now',
    artist: 'Lady Antebellum',
    difficulty: 2,
    genre: 'Country',
    chords: ['D', 'A', 'Bm', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 76,
  ),
  SongData(
    id: 'achy-breaky-heart',
    title: 'Achy Breaky Heart',
    artist: 'Billy Ray Cyrus',
    difficulty: 2,
    genre: 'Country',
    chords: ['D', 'A'],
    lessonRef: 'module_1/lesson_1',
    bpm: 140,
  ),
  SongData(
    id: 'boots',
    title: 'These Boots Are Made for Walkin\'',
    artist: 'Nancy Sinatra',
    difficulty: 2,
    genre: 'Country',
    chords: ['C', 'F', 'G'],
    lessonRef: 'module_1/lesson_1',
    bpm: 108,
  ),
  SongData(
    id: 'the-gambler',
    title: 'The Gambler',
    artist: 'Kenny Rogers',
    difficulty: 2,
    genre: 'Country',
    chords: ['D', 'G', 'A', 'Bm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 108,
  ),
  SongData(
    id: 'mama-tried',
    title: 'Mama Tried',
    artist: 'Merle Haggard',
    difficulty: 2,
    genre: 'Country',
    chords: ['G', 'C', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 132,
  ),
  SongData(
    id: 'on-the-road-again',
    title: 'On the Road Again',
    artist: 'Willie Nelson',
    difficulty: 2,
    genre: 'Country',
    chords: ['E', 'A', 'F#m', 'B7'],
    lessonRef: 'module_1/lesson_1',
    bpm: 104,
  ),
  SongData(
    id: 'whiskey-in-the-jar',
    title: 'Whiskey in the Jar',
    artist: 'Thin Lizzy',
    difficulty: 2,
    genre: 'Country',
    chords: ['G', 'Em', 'C', 'D'],
    lessonRef: 'module_1/lesson_1',
    bpm: 104,
  ),
  SongData(
    id: 'copperhead-road',
    title: 'Copperhead Road',
    artist: 'Steve Earle',
    difficulty: 3,
    genre: 'Country',
    chords: ['D5', 'G5', 'A5'],
    lessonRef: 'module_1/lesson_1',
    bpm: 144,
  ),
  SongData(
    id: 'fast-as-you',
    title: 'Fast as You',
    artist: 'Dwight Yoakam',
    difficulty: 3,
    genre: 'Country',
    chords: ['D', 'G', 'A', 'E'],
    lessonRef: 'module_1/lesson_1',
    bpm: 160,
  ),
  SongData(
    id: 'the-devil-went-down-to-georgia',
    title: 'The Devil Went Down to Georgia',
    artist: 'Charlie Daniels Band',
    difficulty: 3,
    genre: 'Country',
    chords: ['Dm', 'C', 'G', 'A'],
    lessonRef: 'module_1/lesson_1',
    bpm: 220,
  ),
  SongData(
    id: 'pancho-and-lefty',
    title: 'Pancho & Lefty',
    artist: 'Townes Van Zandt',
    difficulty: 3,
    genre: 'Country',
    chords: ['G', 'C', 'D', 'Em', 'Am'],
    lessonRef: 'module_1/lesson_1',
    bpm: 88,
  ),
  SongData(
    id: 'brand-new-key',
    title: 'Brand New Key',
    artist: 'Melanie',
    difficulty: 3,
    genre: 'Country',
    chords: ['D', 'G', 'A7', 'Bm'],
    lessonRef: 'module_1/lesson_1',
    bpm: 148,
  ),
];

class SongLibraryScreen extends ConsumerStatefulWidget {
  const SongLibraryScreen({super.key});

  @override
  ConsumerState<SongLibraryScreen> createState() => _SongLibraryScreenState();
}

class _SongLibraryScreenState extends ConsumerState<SongLibraryScreen> {
  String? _activeGenre; // null = 'Alle'
  final Set<int> _diffFilter = {};

  /// All unique genres, sorted alphabetically.
  static final List<String> _sortedGenres = () {
    final genres = kSongs.map((s) => s.genre).toSet().toList()..sort();
    return genres;
  }();

  /// Count of songs per genre.
  static final Map<String, int> _genreCount = () {
    final map = <String, int>{};
    for (final s in kSongs) {
      map[s.genre] = (map[s.genre] ?? 0) + 1;
    }
    return map;
  }();

  List<SongData> get _filtered {
    final list = kSongs.where((s) {
      final gOk = _activeGenre == null || s.genre == _activeGenre;
      final dOk = _diffFilter.isEmpty || _diffFilter.contains(s.difficulty);
      return gOk && dOk;
    }).toList()
      ..sort((a, b) => a.difficulty.compareTo(b.difficulty));
    return list;
  }

  @override
  Widget build(BuildContext context) {
    final songs = _filtered;
    return Scaffold(
      appBar: AppBar(title: const Text('Songs')),
      body: Column(
        children: [
          // ── Genre filter ─────────────────────────────────────────────────
          SizedBox(
            height: 44,
            child: ListView(
              scrollDirection: Axis.horizontal,
              padding: const EdgeInsets.symmetric(horizontal: 12),
              children: [
                // 'Alle' chip first
                Padding(
                  padding: const EdgeInsets.only(right: 8),
                  child: FilterChip(
                    label: Text('Alle (${kSongs.length})'),
                    selected: _activeGenre == null,
                    onSelected: (_) => setState(() => _activeGenre = null),
                  ),
                ),
                for (final g in _sortedGenres)
                  Padding(
                    padding: const EdgeInsets.only(right: 8),
                    child: FilterChip(
                      label: Text('$g (${_genreCount[g]})'),
                      selected: _activeGenre == g,
                      onSelected: (sel) =>
                          setState(() => _activeGenre = sel ? g : null),
                    ),
                  ),
              ],
            ),
          ),
          // ── Difficulty filter ────────────────────────────────────────────
          SizedBox(
            height: 44,
            child: ListView(
              scrollDirection: Axis.horizontal,
              padding: const EdgeInsets.symmetric(horizontal: 12),
              children: [
                for (int d = 1; d <= 3; d++)
                  Padding(
                    padding: const EdgeInsets.only(right: 8),
                    child: FilterChip(
                      label: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: List.generate(
                          d,
                          (_) => const Icon(Icons.star,
                              size: 14, color: AppColors.xpColor),
                        ),
                      ),
                      selected: _diffFilter.contains(d),
                      onSelected: (sel) => setState(() {
                        if (sel) {
                          _diffFilter.add(d);
                        } else {
                          _diffFilter.remove(d);
                        }
                      }),
                    ),
                  ),
              ],
            ),
          ),
          const SizedBox(height: 8),
          // ── Song list ────────────────────────────────────────────────────
          Expanded(
            child: songs.isEmpty
                ? const Center(child: Text('Keine Songs gefunden'))
                : ListView.builder(
                    padding: const EdgeInsets.symmetric(horizontal: 12),
                    itemCount: songs.length,
                    itemBuilder: (context, i) {
                      final s = songs[i];
                      return Card(
                        color: AppColors.cardDark,
                        child: ListTile(
                          leading: CircleAvatar(
                            backgroundColor: AppColors.primary,
                            child: Text(
                              s.title.substring(0, 1),
                              style: const TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                          title: Text(
                            s.title,
                            style: const TextStyle(
                              color: AppColors.textPrimary,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                          subtitle: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                s.artist,
                                style: const TextStyle(
                                  color: AppColors.textSecondary,
                                ),
                              ),
                              const SizedBox(height: 4),
                              Row(
                                children: [
                                  // Difficulty stars
                                  ...List.generate(
                                    s.difficulty,
                                    (_) => const Icon(Icons.star,
                                        size: 12,
                                        color: AppColors.xpColor),
                                  ),
                                  const SizedBox(width: 8),
                                  // Genre label
                                  Text(
                                    s.genre,
                                    style: const TextStyle(
                                      color: AppColors.textTertiary,
                                      fontSize: 12,
                                    ),
                                  ),
                                  const SizedBox(width: 8),
                                  // BPM
                                  Text(
                                    '♩ ${s.bpm} BPM',
                                    style: const TextStyle(
                                      color: AppColors.textTertiary,
                                      fontSize: 11,
                                    ),
                                  ),
                                  if (s.tuning != 'Standard') ...[
                                    const SizedBox(width: 6),
                                    // Tuning badge
                                    Container(
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 5, vertical: 1),
                                      decoration: BoxDecoration(
                                        color: AppColors.primary
                                            .withValues(alpha: 0.25),
                                        borderRadius: BorderRadius.circular(4),
                                      ),
                                      child: Text(
                                        s.tuning,
                                        style: const TextStyle(
                                          color: AppColors.primary,
                                          fontSize: 10,
                                          fontWeight: FontWeight.w600,
                                        ),
                                      ),
                                    ),
                                  ],
                                ],
                              ),
                            ],
                          ),
                          trailing: const Icon(
                            Icons.chevron_right,
                            color: AppColors.textSecondary,
                          ),
                          onTap: () => context.go('/home/songs/${s.id}'),
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}
